<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwCameraMovement;

/**
 * Camera Movement Seeder
 *
 * Seeds 25+ professional camera movements based on:
 * - Higgsfield's 50+ cinematic motion presets
 * - Traditional Hollywood cinematography techniques
 * - AI video generation best practices
 */
class VwCameraMovementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movements = [
            // ===== ZOOM CATEGORY =====
            [
                'slug' => 'zoom-in',
                'name' => 'Zoom In',
                'category' => 'zoom',
                'description' => 'Camera lens zooms in toward subject. Creates emphasis and draws attention.',
                'prompt_syntax' => 'camera slowly zooms in on the subject',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['pan-left', 'pan-right', 'tilt-up', 'tilt-down']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'medium-close']),
                'best_for_emotions' => json_encode(['emphasis', 'focus', 'tension', 'reveal']),
                'natural_continuation' => 'static',
                'ending_state' => 'closer to subject, tighter framing',
                'sort_order' => 1,
            ],
            [
                'slug' => 'zoom-out',
                'name' => 'Zoom Out',
                'category' => 'zoom',
                'description' => 'Camera lens zooms out from subject. Reveals context and environment.',
                'prompt_syntax' => 'camera slowly zooms out revealing the environment',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['pan-left', 'pan-right', 'crane-up']),
                'best_for_shot_types' => json_encode(['close-up', 'medium', 'medium-close']),
                'best_for_emotions' => json_encode(['reveal', 'context', 'isolation', 'conclusion']),
                'natural_continuation' => 'static',
                'ending_state' => 'further from subject, wider framing',
                'sort_order' => 2,
            ],
            [
                'slug' => 'crash-zoom-in',
                'name' => 'Crash Zoom In',
                'category' => 'zoom',
                'description' => 'Rapid, dramatic zoom toward subject. High-impact emphasis.',
                'prompt_syntax' => 'rapid crash zoom in on the subject',
                'intensity' => 'intense',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'wide']),
                'best_for_emotions' => json_encode(['shock', 'impact', 'drama', 'realization']),
                'natural_continuation' => 'static',
                'ending_state' => 'tight on subject, dramatic emphasis',
                'sort_order' => 3,
            ],
            [
                'slug' => 'dolly-zoom',
                'name' => 'Dolly Zoom (Vertigo)',
                'category' => 'zoom',
                'description' => 'Dolly out while zooming in (or vice versa). Creates disorienting vertigo effect.',
                'prompt_syntax' => 'dolly zoom creating vertigo effect, background warping',
                'intensity' => 'dynamic',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'medium-close']),
                'best_for_emotions' => json_encode(['disorientation', 'realization', 'fear', 'revelation']),
                'natural_continuation' => 'static',
                'ending_state' => 'subject same size, background distorted',
                'sort_order' => 4,
            ],

            // ===== DOLLY CATEGORY =====
            [
                'slug' => 'dolly-in',
                'name' => 'Dolly In',
                'category' => 'dolly',
                'description' => 'Camera physically moves toward subject on dolly/track. Creates intimacy.',
                'prompt_syntax' => 'camera smoothly dollies in toward the subject',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['crane-up', 'crane-down', 'pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'full']),
                'best_for_emotions' => json_encode(['intimacy', 'tension', 'focus', 'connection']),
                'natural_continuation' => 'dolly-out',
                'ending_state' => 'closer to subject with depth',
                'sort_order' => 10,
            ],
            [
                'slug' => 'dolly-out',
                'name' => 'Dolly Out',
                'category' => 'dolly',
                'description' => 'Camera physically moves away from subject. Reveals space and creates distance.',
                'prompt_syntax' => 'camera smoothly dollies out from the subject',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['crane-up', 'crane-down']),
                'best_for_shot_types' => json_encode(['close-up', 'medium', 'medium-close']),
                'best_for_emotions' => json_encode(['reveal', 'departure', 'isolation', 'conclusion']),
                'natural_continuation' => 'static',
                'ending_state' => 'further from subject with spatial context',
                'sort_order' => 11,
            ],
            [
                'slug' => 'tracking-left',
                'name' => 'Track Left',
                'category' => 'dolly',
                'description' => 'Camera moves laterally to the left, following or revealing.',
                'prompt_syntax' => 'camera tracks laterally to the left',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out', 'crane-up']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'full']),
                'best_for_emotions' => json_encode(['journey', 'follow', 'reveal', 'exploration']),
                'natural_continuation' => 'tracking-right',
                'ending_state' => 'camera repositioned left of starting point',
                'sort_order' => 12,
            ],
            [
                'slug' => 'tracking-right',
                'name' => 'Track Right',
                'category' => 'dolly',
                'description' => 'Camera moves laterally to the right, following or revealing.',
                'prompt_syntax' => 'camera tracks laterally to the right',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out', 'crane-up']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'full']),
                'best_for_emotions' => json_encode(['journey', 'follow', 'reveal', 'exploration']),
                'natural_continuation' => 'tracking-left',
                'ending_state' => 'camera repositioned right of starting point',
                'sort_order' => 13,
            ],
            [
                'slug' => 'push-in',
                'name' => 'Push In',
                'category' => 'dolly',
                'description' => 'Slow, subtle dolly toward subject. Emphasizes emotion without drama.',
                'prompt_syntax' => 'camera slowly pushes in toward the subject',
                'intensity' => 'subtle',
                'typical_duration_min' => 4,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['tilt-up', 'tilt-down']),
                'best_for_shot_types' => json_encode(['medium', 'medium-close', 'close-up']),
                'best_for_emotions' => json_encode(['intimacy', 'emotion', 'focus', 'realization']),
                'natural_continuation' => 'static',
                'ending_state' => 'slightly closer, emotional emphasis',
                'sort_order' => 14,
            ],
            [
                'slug' => 'pull-back',
                'name' => 'Pull Back',
                'category' => 'dolly',
                'description' => 'Camera pulls away from subject, often revealing environment.',
                'prompt_syntax' => 'camera pulls back revealing the environment',
                'intensity' => 'moderate',
                'typical_duration_min' => 4,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['crane-up']),
                'best_for_shot_types' => json_encode(['close-up', 'medium', 'medium-close']),
                'best_for_emotions' => json_encode(['reveal', 'conclusion', 'context', 'departure']),
                'natural_continuation' => 'static',
                'ending_state' => 'wider view with environmental context',
                'sort_order' => 15,
            ],

            // ===== CRANE CATEGORY =====
            [
                'slug' => 'crane-up',
                'name' => 'Crane Up',
                'category' => 'crane',
                'description' => 'Camera rises vertically. Creates epic feeling and reveals scale.',
                'prompt_syntax' => 'camera cranes up smoothly rising above',
                'intensity' => 'moderate',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out', 'pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['medium', 'full', 'wide']),
                'best_for_emotions' => json_encode(['epic', 'triumph', 'reveal', 'conclusion']),
                'natural_continuation' => 'crane-down',
                'ending_state' => 'elevated perspective, looking down',
                'sort_order' => 20,
            ],
            [
                'slug' => 'crane-down',
                'name' => 'Crane Down',
                'category' => 'crane',
                'description' => 'Camera descends vertically. Approaches subject or reveals ground-level detail.',
                'prompt_syntax' => 'camera cranes down smoothly descending',
                'intensity' => 'moderate',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out']),
                'best_for_shot_types' => json_encode(['wide', 'extreme-wide', 'aerial']),
                'best_for_emotions' => json_encode(['approach', 'arrival', 'reveal', 'grounding']),
                'natural_continuation' => 'static',
                'ending_state' => 'lower perspective, approaching subject',
                'sort_order' => 21,
            ],
            [
                'slug' => 'jib-up',
                'name' => 'Jib Up',
                'category' => 'crane',
                'description' => 'Short vertical rise using jib arm. More subtle than full crane.',
                'prompt_syntax' => 'camera jibs up slightly elevating',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode(['pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['medium', 'medium-wide']),
                'best_for_emotions' => json_encode(['subtle-reveal', 'transition', 'elevation']),
                'natural_continuation' => 'jib-down',
                'ending_state' => 'slightly elevated perspective',
                'sort_order' => 22,
            ],
            [
                'slug' => 'jib-down',
                'name' => 'Jib Down',
                'category' => 'crane',
                'description' => 'Short vertical descent using jib arm.',
                'prompt_syntax' => 'camera jibs down slightly descending',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode(['pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['medium', 'medium-wide']),
                'best_for_emotions' => json_encode(['approach', 'grounding', 'settling']),
                'natural_continuation' => 'static',
                'ending_state' => 'slightly lowered perspective',
                'sort_order' => 23,
            ],

            // ===== PAN & TILT CATEGORY =====
            [
                'slug' => 'pan-left',
                'name' => 'Pan Left',
                'category' => 'pan_tilt',
                'description' => 'Camera rotates horizontally to the left. Follows action or scans environment.',
                'prompt_syntax' => 'camera pans left',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['dolly-in', 'crane-up', 'crane-down', 'tilt-up']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'establishing']),
                'best_for_emotions' => json_encode(['follow', 'scan', 'reveal', 'connection']),
                'natural_continuation' => 'pan-right',
                'ending_state' => 'rotated left, new framing',
                'sort_order' => 30,
            ],
            [
                'slug' => 'pan-right',
                'name' => 'Pan Right',
                'category' => 'pan_tilt',
                'description' => 'Camera rotates horizontally to the right.',
                'prompt_syntax' => 'camera pans right',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode(['dolly-in', 'crane-up', 'crane-down', 'tilt-up']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'establishing']),
                'best_for_emotions' => json_encode(['follow', 'scan', 'reveal', 'connection']),
                'natural_continuation' => 'pan-left',
                'ending_state' => 'rotated right, new framing',
                'sort_order' => 31,
            ],
            [
                'slug' => 'tilt-up',
                'name' => 'Tilt Up',
                'category' => 'pan_tilt',
                'description' => 'Camera rotates vertically upward. Reveals height or scans vertically.',
                'prompt_syntax' => 'camera tilts up',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out', 'pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['full', 'medium', 'wide']),
                'best_for_emotions' => json_encode(['reveal', 'scale', 'power', 'discovery']),
                'natural_continuation' => 'tilt-down',
                'ending_state' => 'angled upward',
                'sort_order' => 32,
            ],
            [
                'slug' => 'tilt-down',
                'name' => 'Tilt Down',
                'category' => 'pan_tilt',
                'description' => 'Camera rotates vertically downward.',
                'prompt_syntax' => 'camera tilts down',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode(['dolly-in', 'dolly-out', 'pan-left', 'pan-right']),
                'best_for_shot_types' => json_encode(['wide', 'medium', 'establishing']),
                'best_for_emotions' => json_encode(['reveal', 'approach', 'focus', 'grounding']),
                'natural_continuation' => 'static',
                'ending_state' => 'angled downward',
                'sort_order' => 33,
            ],
            [
                'slug' => 'whip-pan',
                'name' => 'Whip Pan',
                'category' => 'pan_tilt',
                'description' => 'Extremely fast pan creating motion blur. Used for transitions or energy.',
                'prompt_syntax' => 'fast whip pan with motion blur',
                'intensity' => 'intense',
                'typical_duration_min' => 1,
                'typical_duration_max' => 3,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'wide']),
                'best_for_emotions' => json_encode(['transition', 'energy', 'surprise', 'time-passage']),
                'natural_continuation' => 'static',
                'ending_state' => 'new subject/framing after blur',
                'sort_order' => 34,
            ],

            // ===== ARC CATEGORY =====
            [
                'slug' => 'arc-left',
                'name' => 'Arc Left',
                'category' => 'arc',
                'description' => 'Camera moves in arc around subject to the left.',
                'prompt_syntax' => 'camera arcs around the subject to the left',
                'intensity' => 'moderate',
                'typical_duration_min' => 4,
                'typical_duration_max' => 12,
                'stackable_with' => json_encode(['dolly-in', 'crane-up']),
                'best_for_shot_types' => json_encode(['medium', 'medium-close', 'full']),
                'best_for_emotions' => json_encode(['drama', 'reveal', 'tension', 'showcase']),
                'natural_continuation' => 'arc-right',
                'ending_state' => 'repositioned around subject',
                'sort_order' => 40,
            ],
            [
                'slug' => 'arc-right',
                'name' => 'Arc Right',
                'category' => 'arc',
                'description' => 'Camera moves in arc around subject to the right.',
                'prompt_syntax' => 'camera arcs around the subject to the right',
                'intensity' => 'moderate',
                'typical_duration_min' => 4,
                'typical_duration_max' => 12,
                'stackable_with' => json_encode(['dolly-in', 'crane-up']),
                'best_for_shot_types' => json_encode(['medium', 'medium-close', 'full']),
                'best_for_emotions' => json_encode(['drama', 'reveal', 'tension', 'showcase']),
                'natural_continuation' => 'arc-left',
                'ending_state' => 'repositioned around subject',
                'sort_order' => 41,
            ],
            [
                'slug' => 'orbit-360',
                'name' => '360 Orbit',
                'category' => 'arc',
                'description' => 'Camera orbits full 360 degrees around subject.',
                'prompt_syntax' => 'camera orbits 360 degrees around the subject',
                'intensity' => 'dynamic',
                'typical_duration_min' => 6,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'full']),
                'best_for_emotions' => json_encode(['showcase', 'drama', 'climax', 'hero']),
                'natural_continuation' => 'static',
                'ending_state' => 'returned to starting position',
                'sort_order' => 42,
            ],

            // ===== SPECIALTY CATEGORY =====
            [
                'slug' => 'static',
                'name' => 'Static',
                'category' => 'specialty',
                'description' => 'Camera remains completely still. Action happens within frame.',
                'prompt_syntax' => 'camera remains static, locked off',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['all']),
                'best_for_emotions' => json_encode(['stability', 'observation', 'tension-build', 'contemplation']),
                'natural_continuation' => null,
                'ending_state' => 'same as starting position',
                'sort_order' => 50,
            ],
            [
                'slug' => 'handheld',
                'name' => 'Handheld',
                'category' => 'specialty',
                'description' => 'Organic handheld movement with subtle shake. Documentary feel.',
                'prompt_syntax' => 'handheld camera with subtle organic movement',
                'intensity' => 'subtle',
                'typical_duration_min' => 3,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'close-up', 'pov']),
                'best_for_emotions' => json_encode(['realism', 'urgency', 'documentary', 'tension']),
                'natural_continuation' => 'static',
                'ending_state' => 'similar framing with organic movement',
                'sort_order' => 51,
            ],
            [
                'slug' => 'steadicam-follow',
                'name' => 'Steadicam Follow',
                'category' => 'specialty',
                'description' => 'Smooth stabilized movement following subject through space.',
                'prompt_syntax' => 'steadicam smoothly follows the subject',
                'intensity' => 'moderate',
                'typical_duration_min' => 5,
                'typical_duration_max' => 20,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['medium', 'full', 'wide']),
                'best_for_emotions' => json_encode(['immersion', 'journey', 'flow', 'tension']),
                'natural_continuation' => 'static',
                'ending_state' => 'new location following subject',
                'sort_order' => 52,
            ],
            [
                'slug' => 'fpv-drone',
                'name' => 'FPV Drone',
                'category' => 'specialty',
                'description' => 'Dynamic first-person-view drone movement through environment.',
                'prompt_syntax' => 'FPV drone flying dynamically through the scene',
                'intensity' => 'dynamic',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['wide', 'establishing', 'aerial']),
                'best_for_emotions' => json_encode(['energy', 'excitement', 'exploration', 'speed']),
                'natural_continuation' => 'static',
                'ending_state' => 'new perspective after flight',
                'sort_order' => 53,
            ],
            [
                'slug' => 'aerial-pullback',
                'name' => 'Aerial Pullback',
                'category' => 'specialty',
                'description' => 'Drone/aerial camera pulls back and up revealing vast environment.',
                'prompt_syntax' => 'aerial camera pulls back and up revealing vast landscape',
                'intensity' => 'dynamic',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'stackable_with' => json_encode([]),
                'best_for_shot_types' => json_encode(['wide', 'extreme-wide', 'establishing']),
                'best_for_emotions' => json_encode(['epic', 'scale', 'conclusion', 'isolation']),
                'natural_continuation' => 'static',
                'ending_state' => 'high above, vast view',
                'sort_order' => 54,
            ],
            [
                'slug' => 'rack-focus',
                'name' => 'Rack Focus',
                'category' => 'specialty',
                'description' => 'Focus shifts between foreground and background subjects.',
                'prompt_syntax' => 'focus racks from foreground to background',
                'intensity' => 'subtle',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'stackable_with' => json_encode(['static', 'push-in']),
                'best_for_shot_types' => json_encode(['medium', 'close-up', 'over-shoulder']),
                'best_for_emotions' => json_encode(['connection', 'reveal', 'transition', 'emphasis']),
                'natural_continuation' => 'static',
                'ending_state' => 'focus on new subject',
                'sort_order' => 55,
            ],
            [
                'slug' => 'dutch-angle',
                'name' => 'Dutch Angle',
                'category' => 'specialty',
                'description' => 'Camera tilted on axis creating unease or stylized feel.',
                'prompt_syntax' => 'dutch angle tilted camera creating unease',
                'intensity' => 'moderate',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'stackable_with' => json_encode(['push-in', 'dolly-in']),
                'best_for_shot_types' => json_encode(['medium', 'close-up', 'wide']),
                'best_for_emotions' => json_encode(['unease', 'tension', 'disorientation', 'madness']),
                'natural_continuation' => 'static',
                'ending_state' => 'tilted perspective',
                'sort_order' => 56,
            ],
        ];

        // Seedance 2.0 compatibility data for each movement.
        // Format: slug => [seedance_compatible, seedance_prompt_syntax, seedance_shot_size]
        $seedanceData = [
            'zoom-in'          => [true, 'Push-in, Eye-level, Normal lens', 'close'],
            'zoom-out'         => [true, 'Pull-out, Eye-level, Normal lens', 'wide'],
            'crash-zoom-in'    => [false, null, null],
            'dolly-zoom'       => [false, null, null],
            'dolly-in'         => [true, 'Dolly, Eye-level, Normal lens', 'medium'],
            'dolly-out'        => [true, 'Dolly, Eye-level, Normal lens', 'wide'],
            'tracking-left'    => [true, 'Tracking shot, Eye-level, Normal lens', 'medium'],
            'tracking-right'   => [true, 'Tracking shot, Eye-level, Normal lens', 'medium'],
            'push-in'          => [true, 'Push-in, Eye-level, Normal lens', 'close'],
            'pull-back'        => [true, 'Pull-out, Eye-level, Normal lens', 'wide'],
            'crane-up'         => [true, 'Crane shot, Low-angle, Wide lens', 'wide'],
            'crane-down'       => [true, 'Crane shot, High-angle, Wide lens', 'wide'],
            'jib-up'           => [true, 'Crane shot, Eye-level, Normal lens', 'medium'],
            'jib-down'         => [true, 'Crane shot, Eye-level, Normal lens', 'medium'],
            'pan-left'         => [true, 'Pan, Eye-level, Normal lens', 'medium'],
            'pan-right'        => [true, 'Pan, Eye-level, Normal lens', 'medium'],
            'tilt-up'          => [true, 'Tilt-up, Eye-level, Normal lens', 'medium'],
            'tilt-down'        => [true, 'Tilt-down, Eye-level, Normal lens', 'medium'],
            'whip-pan'         => [false, null, null],
            'arc-left'         => [true, 'Steadicam orbit, Eye-level, Normal lens', 'medium'],
            'arc-right'        => [true, 'Steadicam orbit, Eye-level, Normal lens', 'medium'],
            'orbit-360'        => [true, 'Steadicam orbit, Eye-level, Normal lens', 'medium'],
            'static'           => [true, 'Locked-off, Eye-level, Normal lens', 'medium'],
            'handheld'         => [true, 'Handheld, Eye-level, Normal lens', 'medium'],
            'steadicam-follow' => [true, 'Steadicam, Eye-level, Normal lens', 'medium'],
            'fpv-drone'        => [true, 'Overhead, Bird\'s-eye, Wide lens', 'wide'],
            'aerial-pullback'  => [true, 'Overhead, Bird\'s-eye, Wide lens', 'wide'],
            'rack-focus'       => [false, null, null],
            'dutch-angle'      => [true, 'Dutch angle, Tilted, Normal lens', 'medium'],
        ];

        foreach ($movements as $movement) {
            $slug = $movement['slug'];
            $seedance = $seedanceData[$slug] ?? [true, null, null];

            VwCameraMovement::updateOrCreate(
                ['slug' => $slug],
                array_merge($movement, [
                    'is_active' => true,
                    'seedance_compatible' => $seedance[0],
                    'seedance_prompt_syntax' => $seedance[1],
                    'seedance_shot_size' => $seedance[2],
                ])
            );
        }
    }
}
