<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwCameraSpec;

class VwCameraSpecSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Professional camera specifications based on Sora 2 best practices.
     */
    public function run(): void
    {
        $specs = [
            // ===== WIDE LENSES =====
            [
                'slug' => 'ultra-wide-14',
                'name' => 'Ultra-Wide 14mm',
                'category' => 'lens',
                'focal_length' => '14mm',
                'aperture' => 'f/2.8',
                'characteristics' => 'Extreme perspective distortion, dramatic field of view, immersive feel, architectural distortion',
                'prompt_text' => 'shot on ultra-wide 14mm lens, dramatic perspective distortion, expansive field of view, immersive depth',
                'best_for_shots' => json_encode(['extreme-wide', 'establishing', 'pov', 'aerial']),
                'best_for_genres' => json_encode(['epic', 'documentary', 'action', 'experimental']),
                'sort_order' => 1,
            ],
            [
                'slug' => 'wide-18',
                'name' => 'Wide Angle 18mm',
                'category' => 'lens',
                'focal_length' => '18mm',
                'aperture' => 'f/2.8',
                'characteristics' => 'Very wide field of view, noticeable perspective, good for interiors, environmental emphasis',
                'prompt_text' => 'shot on wide 18mm lens, expansive environmental framing, slight perspective distortion',
                'best_for_shots' => json_encode(['very-wide', 'establishing', 'interior-wide']),
                'best_for_genres' => json_encode(['documentary', 'horror', 'thriller']),
                'sort_order' => 2,
            ],
            [
                'slug' => 'wide-24',
                'name' => 'Wide Angle 24mm',
                'category' => 'lens',
                'focal_length' => '24mm',
                'aperture' => 'f/1.4',
                'characteristics' => 'Classic wide angle, environmental storytelling, subtle distortion, versatile wide',
                'prompt_text' => 'shot on 24mm wide-angle lens, environmental storytelling, cinematic depth, natural perspective',
                'best_for_shots' => json_encode(['wide', 'establishing', 'tracking', 'steadicam']),
                'best_for_genres' => json_encode(['all']),
                'sort_order' => 3,
            ],
            [
                'slug' => 'wide-28',
                'name' => 'Wide 28mm',
                'category' => 'lens',
                'focal_length' => '28mm',
                'aperture' => 'f/2',
                'characteristics' => 'Moderate wide angle, documentary favorite, natural perspective with context',
                'prompt_text' => 'shot on 28mm lens, balanced wide framing, documentary authenticity',
                'best_for_shots' => json_encode(['wide', 'medium-wide', 'tracking']),
                'best_for_genres' => json_encode(['documentary', 'drama', 'indie']),
                'sort_order' => 4,
            ],

            // ===== STANDARD LENSES =====
            [
                'slug' => 'standard-35',
                'name' => 'Standard Wide 35mm',
                'category' => 'lens',
                'focal_length' => '35mm',
                'aperture' => 'f/1.4',
                'characteristics' => 'Natural perspective, versatile storytelling lens, documentary standard, human eye-like',
                'prompt_text' => 'shot on 35mm lens, natural human perspective, classic cinematography, versatile framing',
                'best_for_shots' => json_encode(['wide', 'medium-wide', 'tracking', 'master', 'handheld']),
                'best_for_genres' => json_encode(['all']),
                'sort_order' => 10,
            ],
            [
                'slug' => 'standard-40',
                'name' => 'Standard 40mm',
                'category' => 'lens',
                'focal_length' => '40mm',
                'aperture' => 'f/2',
                'characteristics' => 'Slightly wide of normal, natural perspective, great for dialogue, unobtrusive',
                'prompt_text' => 'shot on 40mm lens, natural unobtrusive framing, conversational perspective',
                'best_for_shots' => json_encode(['medium-wide', 'medium', 'two-shot', 'dialogue']),
                'best_for_genres' => json_encode(['drama', 'documentary', 'indie']),
                'sort_order' => 11,
            ],
            [
                'slug' => 'standard-50',
                'name' => 'Standard 50mm',
                'category' => 'lens',
                'focal_length' => '50mm',
                'aperture' => 'f/1.2',
                'characteristics' => 'Human eye perspective, classic nifty fifty, natural compression, versatile portrait',
                'prompt_text' => 'shot on 50mm lens at f/1.2, natural human eye perspective, classic cinematography, beautiful bokeh',
                'best_for_shots' => json_encode(['medium', 'medium-close', 'dialogue', 'portrait']),
                'best_for_genres' => json_encode(['all']),
                'sort_order' => 12,
            ],

            // ===== PORTRAIT/TELEPHOTO LENSES =====
            [
                'slug' => 'portrait-85',
                'name' => 'Portrait 85mm',
                'category' => 'lens',
                'focal_length' => '85mm',
                'aperture' => 'f/1.4',
                'characteristics' => 'Classic portrait lens, flattering compression, creamy bokeh, intimate isolation',
                'prompt_text' => 'shot on 85mm portrait lens at f/1.4, beautiful creamy bokeh, flattering compression, intimate framing',
                'best_for_shots' => json_encode(['close-up', 'medium-close', 'portrait', 'reaction']),
                'best_for_genres' => json_encode(['drama', 'romance', 'documentary', 'portrait']),
                'sort_order' => 20,
            ],
            [
                'slug' => 'portrait-100',
                'name' => 'Portrait 100mm',
                'category' => 'lens',
                'focal_length' => '100mm',
                'aperture' => 'f/2',
                'characteristics' => 'Strong compression, excellent subject isolation, smooth bokeh, intimate distance',
                'prompt_text' => 'shot on 100mm lens at f/2, compressed perspective, strong subject isolation, smooth background',
                'best_for_shots' => json_encode(['close-up', 'big-close-up', 'reaction', 'portrait']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'documentary']),
                'sort_order' => 21,
            ],
            [
                'slug' => 'telephoto-135',
                'name' => 'Telephoto 135mm',
                'category' => 'lens',
                'focal_length' => '135mm',
                'aperture' => 'f/2',
                'characteristics' => 'Strong compression, voyeuristic feel, extreme subject isolation, surveillance aesthetic',
                'prompt_text' => 'shot on 135mm telephoto lens, compressed perspective, extreme subject isolation, voyeuristic framing',
                'best_for_shots' => json_encode(['close-up', 'big-close-up', 'reaction', 'surveillance']),
                'best_for_genres' => json_encode(['thriller', 'drama', 'spy']),
                'sort_order' => 22,
            ],
            [
                'slug' => 'long-telephoto-200',
                'name' => 'Long Telephoto 200mm',
                'category' => 'lens',
                'focal_length' => '200mm',
                'aperture' => 'f/2.8',
                'characteristics' => 'Extreme compression, distant observation, flattened perspective, sports/wildlife aesthetic',
                'prompt_text' => 'shot on 200mm telephoto lens, extreme compression, distant observation, flattened perspective',
                'best_for_shots' => json_encode(['extreme-close-up', 'detail', 'surveillance', 'sports']),
                'best_for_genres' => json_encode(['documentary', 'sports', 'wildlife', 'thriller']),
                'sort_order' => 23,
            ],

            // ===== SPECIALTY LENSES =====
            [
                'slug' => 'macro',
                'name' => 'Macro Lens',
                'category' => 'lens',
                'focal_length' => '100mm macro',
                'aperture' => 'f/2.8',
                'characteristics' => '1:1 magnification, extreme detail, texture revelation, scientific precision',
                'prompt_text' => 'shot on macro lens, extreme detail visible, texture magnified, 1:1 magnification, razor-thin focus',
                'best_for_shots' => json_encode(['extreme-close-up', 'insert', 'detail']),
                'best_for_genres' => json_encode(['documentary', 'product', 'scientific', 'horror']),
                'sort_order' => 30,
            ],
            [
                'slug' => 'anamorphic-40',
                'name' => 'Anamorphic 40mm',
                'category' => 'lens',
                'focal_length' => '40mm anamorphic',
                'aperture' => 'T2',
                'characteristics' => 'Oval bokeh, horizontal lens flares, 2.39:1 widescreen, classic cinema aesthetic',
                'prompt_text' => 'shot on anamorphic lens, oval bokeh, horizontal lens flares, 2.39:1 cinematic widescreen, classic Hollywood',
                'best_for_shots' => json_encode(['establishing', 'wide', 'medium', 'cinematic']),
                'best_for_genres' => json_encode(['cinematic', 'epic', 'sci-fi', 'action']),
                'sort_order' => 31,
            ],
            [
                'slug' => 'anamorphic-75',
                'name' => 'Anamorphic 75mm',
                'category' => 'lens',
                'focal_length' => '75mm anamorphic',
                'aperture' => 'T2',
                'characteristics' => 'Portrait anamorphic, dreamy bokeh ovals, intimate widescreen, cinema close-ups',
                'prompt_text' => 'shot on 75mm anamorphic lens, intimate widescreen framing, oval bokeh, cinematic close-up',
                'best_for_shots' => json_encode(['close-up', 'medium-close', 'portrait']),
                'best_for_genres' => json_encode(['cinematic', 'drama', 'romance']),
                'sort_order' => 32,
            ],
            [
                'slug' => 'tilt-shift',
                'name' => 'Tilt-Shift Lens',
                'category' => 'lens',
                'focal_length' => '45mm tilt-shift',
                'aperture' => 'f/2.8',
                'characteristics' => 'Selective focus plane, miniature effect, dreamlike quality, architectural correction',
                'prompt_text' => 'shot on tilt-shift lens, selective focus plane, dreamlike miniature effect, surreal depth',
                'best_for_shots' => json_encode(['establishing', 'aerial', 'special', 'dream']),
                'best_for_genres' => json_encode(['experimental', 'fantasy', 'commercial']),
                'sort_order' => 33,
            ],

            // ===== FILM STOCKS / LOOKS =====
            [
                'slug' => 'kodak-portra-400',
                'name' => 'Kodak Portra 400',
                'category' => 'film_stock',
                'characteristics' => 'Soft pastels, natural skin tones, fine grain, slightly warm, forgiving highlights',
                'look_description' => 'The gold standard for portrait and fashion film. Soft, pleasing colors with beautiful skin rendering.',
                'prompt_text' => 'Kodak Portra 400 film aesthetic, soft pastel colors, beautiful natural skin tones, fine grain, warm highlights',
                'best_for_shots' => json_encode(['portrait', 'medium', 'close-up']),
                'best_for_genres' => json_encode(['drama', 'romance', 'fashion', 'portrait']),
                'sort_order' => 40,
            ],
            [
                'slug' => 'kodak-vision3-500t',
                'name' => 'Kodak Vision3 500T',
                'category' => 'film_stock',
                'characteristics' => 'Tungsten balanced, cinema standard, rich colors, fine grain, wide latitude',
                'look_description' => 'The film stock used in countless Hollywood productions. Rich, cinematic colors with professional latitude.',
                'prompt_text' => 'Kodak Vision3 500T cinema film look, rich saturated colors, professional motion picture quality, tungsten balanced',
                'best_for_shots' => json_encode(['all']),
                'best_for_genres' => json_encode(['cinematic', 'drama', 'thriller', 'action']),
                'sort_order' => 41,
            ],
            [
                'slug' => 'kodak-vision3-250d',
                'name' => 'Kodak Vision3 250D',
                'category' => 'film_stock',
                'characteristics' => 'Daylight balanced, natural colors, excellent skin tones, subtle grain',
                'look_description' => 'Daylight-balanced cinema film with natural, true-to-life colors and excellent dynamic range.',
                'prompt_text' => 'Kodak Vision3 250D daylight film aesthetic, natural true colors, excellent skin tones, cinematic daylight',
                'best_for_shots' => json_encode(['exterior', 'wide', 'medium']),
                'best_for_genres' => json_encode(['drama', 'documentary', 'romance']),
                'sort_order' => 42,
            ],
            [
                'slug' => 'fuji-velvia-50',
                'name' => 'Fuji Velvia 50',
                'category' => 'film_stock',
                'characteristics' => 'Extremely saturated colors, high contrast, vivid, punchy, landscape favorite',
                'look_description' => 'Legendary slide film known for incredibly vivid, punchy colors. Popular for landscapes and commercial work.',
                'prompt_text' => 'Fuji Velvia film aesthetic, vivid saturated colors, high contrast, punchy vibrant look',
                'best_for_shots' => json_encode(['establishing', 'wide', 'landscape']),
                'best_for_genres' => json_encode(['commercial', 'landscape', 'travel', 'vibrant']),
                'sort_order' => 43,
            ],
            [
                'slug' => 'fuji-provia-100f',
                'name' => 'Fuji Provia 100F',
                'category' => 'film_stock',
                'characteristics' => 'Neutral colors, fine grain, accurate reproduction, professional standard',
                'look_description' => 'Professional slide film with accurate, neutral color reproduction and ultra-fine grain.',
                'prompt_text' => 'Fuji Provia film aesthetic, accurate neutral colors, ultra-fine grain, professional clarity',
                'best_for_shots' => json_encode(['all']),
                'best_for_genres' => json_encode(['commercial', 'product', 'documentary']),
                'sort_order' => 44,
            ],
            [
                'slug' => 'cinestill-800t',
                'name' => 'CineStill 800T',
                'category' => 'film_stock',
                'characteristics' => 'Tungsten balanced, halation glow, neon-friendly, night aesthetic, distinctive red halos',
                'look_description' => 'Cinema film converted for still use. Famous for its halation effect creating dreamy glows around lights.',
                'prompt_text' => 'CineStill 800T aesthetic, tungsten night look, halation glow around lights, neon colors, urban night',
                'best_for_shots' => json_encode(['night', 'establishing', 'wide']),
                'best_for_genres' => json_encode(['noir', 'thriller', 'urban', 'night']),
                'sort_order' => 45,
            ],
            [
                'slug' => 'ilford-hp5',
                'name' => 'Ilford HP5 Plus B&W',
                'category' => 'film_stock',
                'characteristics' => 'Classic black and white, rich midtones, pleasant grain, wide latitude',
                'look_description' => 'Classic black and white film with beautiful tonal range and forgiving exposure latitude.',
                'prompt_text' => 'Ilford HP5 black and white film aesthetic, rich contrast, classic grain, beautiful tonal range',
                'best_for_shots' => json_encode(['all']),
                'best_for_genres' => json_encode(['noir', 'documentary', 'artistic', 'drama']),
                'sort_order' => 46,
            ],
            [
                'slug' => 'kodak-tri-x',
                'name' => 'Kodak Tri-X 400',
                'category' => 'film_stock',
                'characteristics' => 'Iconic B&W, punchy contrast, distinctive grain, photojournalism standard',
                'look_description' => 'The legendary black and white film used by countless photojournalists. Distinctive punchy look.',
                'prompt_text' => 'Kodak Tri-X black and white aesthetic, punchy contrast, iconic grain structure, photojournalistic',
                'best_for_shots' => json_encode(['documentary', 'street', 'portrait']),
                'best_for_genres' => json_encode(['documentary', 'noir', 'street', 'journalism']),
                'sort_order' => 47,
            ],
        ];

        foreach ($specs as $spec) {
            VwCameraSpec::updateOrCreate(
                ['slug' => $spec['slug']],
                array_merge($spec, ['is_active' => true])
            );
        }
    }
}
