<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwCoveragePattern;

/**
 * VwCoveragePatternSeeder - Seeds professional coverage patterns.
 *
 * Based on Hollywood standards and professional filmmaking practices.
 */
class VwCoveragePatternSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patterns = [
            // =============================================
            // DIALOGUE PATTERNS
            // =============================================
            [
                'slug' => 'dialogue-standard',
                'name' => 'Standard Dialogue Coverage',
                'scene_type' => 'dialogue',
                'description' => 'Classic Hollywood dialogue coverage. Establishes scene, shows both characters, then isolates each speaker with over-shoulder and close-up shots.',
                'shot_sequence' => ['master', 'two-shot', 'over-shoulder', 'over-shoulder', 'close-up', 'close-up', 'reaction'],
                'detection_keywords' => ['says', 'asks', 'replies', 'speaks', 'tells', 'conversation', 'dialogue', 'talking', 'discusses', 'explains', 'argues'],
                'negative_keywords' => ['explosion', 'chase', 'fight', 'battle'],
                'visual_cues' => ['two_people', 'seated', 'standing_facing', 'indoor'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 3,
                'max_shots' => 10,
                'typical_shot_duration' => 6,
                'transition_rules' => [
                    'master_to_two-shot' => 'cut',
                    'two-shot_to_over-shoulder' => 'cut',
                    'over-shoulder_to_close-up' => 'cut_on_dialogue',
                ],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'push-in', 'subtle-drift'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 1,
                'priority' => 80,
            ],
            [
                'slug' => 'dialogue-intimate',
                'name' => 'Intimate Dialogue',
                'scene_type' => 'dialogue',
                'description' => 'Close, personal conversation. Skips wide shots, focuses on close-ups and reactions for emotional intimacy.',
                'shot_sequence' => ['medium', 'close-up', 'close-up', 'extreme-close-up', 'reaction'],
                'detection_keywords' => ['whispers', 'confesses', 'intimate', 'secret', 'private', 'quiet', 'tender', 'softly'],
                'negative_keywords' => ['crowd', 'public', 'shouting', 'loud'],
                'visual_cues' => ['close_proximity', 'low_light', 'private_space'],
                'recommended_pacing' => 'slow',
                'min_shots' => 2,
                'max_shots' => 6,
                'typical_shot_duration' => 8,
                'transition_rules' => ['dissolve_allowed' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'slow-push-in'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 2,
                'priority' => 75,
            ],
            [
                'slug' => 'dialogue-confrontation',
                'name' => 'Confrontation Dialogue',
                'scene_type' => 'dialogue',
                'description' => 'Tense argument or confrontation. Uses dynamic angles and closer shots to build tension.',
                'shot_sequence' => ['wide', 'medium', 'over-shoulder', 'close-up', 'close-up', 'reaction', 'two-shot'],
                'detection_keywords' => ['argues', 'yells', 'shouts', 'confronts', 'accuses', 'angry', 'furious', 'demands'],
                'negative_keywords' => ['calm', 'peaceful', 'gentle'],
                'visual_cues' => ['facing_each_other', 'aggressive_posture'],
                'recommended_pacing' => 'fast',
                'min_shots' => 4,
                'max_shots' => 12,
                'typical_shot_duration' => 4,
                'transition_rules' => ['quick_cuts' => true],
                'default_movement_intensity' => 'dynamic',
                'preferred_movements' => ['push-in', 'handheld', 'whip-pan'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 3,
                'priority' => 70,
            ],

            // =============================================
            // ACTION PATTERNS
            // =============================================
            [
                'slug' => 'action-standard',
                'name' => 'Standard Action Sequence',
                'scene_type' => 'action',
                'description' => 'Dynamic action coverage. Wide shots for geography, tracking for movement, close-ups for impact.',
                'shot_sequence' => ['establishing', 'wide', 'tracking', 'medium', 'close-up', 'insert', 'reaction'],
                'detection_keywords' => ['runs', 'fights', 'chases', 'attacks', 'escapes', 'jumps', 'crashes', 'explodes', 'shoots'],
                'negative_keywords' => ['sits', 'waits', 'rests', 'sleeps'],
                'visual_cues' => ['movement', 'outdoor', 'multiple_subjects'],
                'recommended_pacing' => 'fast',
                'min_shots' => 4,
                'max_shots' => 15,
                'typical_shot_duration' => 4,
                'transition_rules' => ['match_cut_on_action' => true],
                'default_movement_intensity' => 'dynamic',
                'preferred_movements' => ['tracking', 'handheld', 'whip-pan', 'crash-zoom'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 10,
                'priority' => 85,
            ],
            [
                'slug' => 'action-chase',
                'name' => 'Chase Sequence',
                'scene_type' => 'action',
                'description' => 'Pursuit coverage. Alternates between pursuer and pursued with tracking and POV shots.',
                'shot_sequence' => ['wide', 'tracking', 'pov', 'medium', 'tracking', 'close-up', 'pov', 'wide'],
                'detection_keywords' => ['chases', 'pursues', 'follows', 'runs from', 'escapes', 'flees', 'racing'],
                'negative_keywords' => ['stationary', 'waiting'],
                'visual_cues' => ['motion_blur', 'vehicles', 'running'],
                'recommended_pacing' => 'fast',
                'min_shots' => 5,
                'max_shots' => 20,
                'typical_shot_duration' => 3,
                'transition_rules' => ['parallel_editing' => true],
                'default_movement_intensity' => 'intense',
                'preferred_movements' => ['tracking', 'dolly', 'handheld', 'aerial'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 11,
                'priority' => 80,
            ],
            [
                'slug' => 'action-fight',
                'name' => 'Fight Sequence',
                'scene_type' => 'action',
                'description' => 'Combat coverage. Wide for choreography, close for impact, inserts for specific strikes.',
                'shot_sequence' => ['wide', 'medium', 'close-up', 'insert', 'reaction', 'medium', 'close-up'],
                'detection_keywords' => ['fights', 'punches', 'kicks', 'strikes', 'attacks', 'blocks', 'combat', 'battle'],
                'negative_keywords' => ['peaceful', 'friendly'],
                'visual_cues' => ['physical_contact', 'combat_stance'],
                'recommended_pacing' => 'dynamic',
                'min_shots' => 4,
                'max_shots' => 15,
                'typical_shot_duration' => 3,
                'transition_rules' => ['impact_cuts' => true],
                'default_movement_intensity' => 'intense',
                'preferred_movements' => ['handheld', 'whip-pan', 'crash-zoom', 'arc'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 12,
                'priority' => 75,
            ],

            // =============================================
            // EMOTIONAL PATTERNS
            // =============================================
            [
                'slug' => 'emotional-standard',
                'name' => 'Emotional Beat',
                'scene_type' => 'emotional',
                'description' => 'Builds emotional intensity through progressive shot sizes, culminating in intimate close-ups.',
                'shot_sequence' => ['wide', 'medium', 'close-up', 'extreme-close-up'],
                'detection_keywords' => ['cries', 'tears', 'emotional', 'heartbreak', 'joy', 'grief', 'overwhelmed', 'moved'],
                'negative_keywords' => ['action', 'fight', 'chase'],
                'visual_cues' => ['facial_expression', 'tears', 'embrace'],
                'recommended_pacing' => 'slow',
                'min_shots' => 2,
                'max_shots' => 6,
                'typical_shot_duration' => 8,
                'transition_rules' => ['hold_on_emotion' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['slow-push-in', 'static', 'gentle-drift'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 20,
                'priority' => 75,
            ],
            [
                'slug' => 'emotional-revelation',
                'name' => 'Revelation Moment',
                'scene_type' => 'emotional',
                'description' => 'Character realizes something important. Builds to the moment of understanding.',
                'shot_sequence' => ['medium', 'close-up', 'insert', 'extreme-close-up', 'reaction'],
                'detection_keywords' => ['realizes', 'discovers', 'understands', 'shocked', 'revelation', 'truth', 'suddenly'],
                'negative_keywords' => [],
                'visual_cues' => ['eye_widening', 'expression_change'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 3,
                'max_shots' => 7,
                'typical_shot_duration' => 6,
                'transition_rules' => ['hold_on_realization' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['push-in', 'static'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 21,
                'priority' => 70,
            ],
            [
                'slug' => 'emotional-grief',
                'name' => 'Grief/Loss Scene',
                'scene_type' => 'emotional',
                'description' => 'Mourning or loss coverage. Respectful distance building to intimate moments.',
                'shot_sequence' => ['wide', 'medium', 'close-up', 'detail', 'extreme-close-up'],
                'detection_keywords' => ['mourns', 'grieves', 'loss', 'funeral', 'death', 'farewell', 'goodbye', 'departed'],
                'negative_keywords' => ['happy', 'celebration', 'party'],
                'visual_cues' => ['subdued_lighting', 'somber', 'isolated'],
                'recommended_pacing' => 'slow',
                'min_shots' => 3,
                'max_shots' => 8,
                'typical_shot_duration' => 10,
                'transition_rules' => ['dissolves_preferred' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'very-slow-push-in'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 22,
                'priority' => 65,
            ],

            // =============================================
            // ESTABLISHING PATTERNS
            // =============================================
            [
                'slug' => 'establishing-location',
                'name' => 'Location Establishing',
                'scene_type' => 'establishing',
                'description' => 'Introduces a new location. Wide shots to orient viewer, then moves to subject.',
                'shot_sequence' => ['extreme-wide', 'wide', 'medium-wide'],
                'detection_keywords' => ['arrives', 'enters', 'location', 'place', 'building', 'city', 'exterior', 'exterior of'],
                'negative_keywords' => ['continues', 'still'],
                'visual_cues' => ['architecture', 'landscape', 'signage'],
                'recommended_pacing' => 'slow',
                'min_shots' => 2,
                'max_shots' => 5,
                'typical_shot_duration' => 6,
                'transition_rules' => ['hold_for_orientation' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['slow-pan', 'aerial', 'crane-down'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 30,
                'priority' => 90,
            ],
            [
                'slug' => 'establishing-time',
                'name' => 'Time Passage Establishing',
                'scene_type' => 'establishing',
                'description' => 'Shows passage of time through location or environmental changes.',
                'shot_sequence' => ['wide', 'detail', 'wide', 'medium'],
                'detection_keywords' => ['later', 'hours pass', 'days later', 'time passes', 'morning', 'evening', 'sunset', 'sunrise'],
                'negative_keywords' => [],
                'visual_cues' => ['sky_change', 'lighting_change', 'clock'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 2,
                'max_shots' => 4,
                'typical_shot_duration' => 5,
                'transition_rules' => ['dissolve_or_timelapse' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'timelapse', 'slow-pan'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 31,
                'priority' => 70,
            ],

            // =============================================
            // MONTAGE PATTERNS
            // =============================================
            [
                'slug' => 'montage-training',
                'name' => 'Training/Preparation Montage',
                'scene_type' => 'montage',
                'description' => 'Shows progress through skill development or preparation. Mix of shot sizes.',
                'shot_sequence' => ['wide', 'medium', 'close-up', 'detail', 'wide', 'medium', 'close-up'],
                'detection_keywords' => ['trains', 'practices', 'prepares', 'improves', 'learns', 'workout', 'montage'],
                'negative_keywords' => [],
                'visual_cues' => ['repetitive_action', 'progression'],
                'recommended_pacing' => 'dynamic',
                'min_shots' => 5,
                'max_shots' => 15,
                'typical_shot_duration' => 4,
                'transition_rules' => ['match_cuts' => true, 'music_driven' => true],
                'default_movement_intensity' => 'moderate',
                'preferred_movements' => ['tracking', 'arc', 'push-in'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 40,
                'priority' => 70,
            ],
            [
                'slug' => 'montage-passage',
                'name' => 'Passage of Time Montage',
                'scene_type' => 'montage',
                'description' => 'Shows events over extended period. Variety of shots connected thematically.',
                'shot_sequence' => ['establishing', 'medium', 'close-up', 'cutaway', 'medium', 'detail'],
                'detection_keywords' => ['months pass', 'years later', 'time flies', 'seasons change', 'growing up'],
                'negative_keywords' => [],
                'visual_cues' => ['changing_seasons', 'aging', 'growth'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 4,
                'max_shots' => 12,
                'typical_shot_duration' => 5,
                'transition_rules' => ['dissolves_and_wipes' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'slow-pan', 'dolly'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 41,
                'priority' => 65,
            ],

            // =============================================
            // SPECIAL PATTERNS
            // =============================================
            [
                'slug' => 'flashback-standard',
                'name' => 'Flashback Sequence',
                'scene_type' => 'flashback',
                'description' => 'Memory or past event coverage. Often uses different visual treatment.',
                'shot_sequence' => ['close-up', 'wide', 'medium', 'close-up'],
                'detection_keywords' => ['remembers', 'recalls', 'memory', 'flashback', 'years ago', 'back then', 'in the past'],
                'negative_keywords' => ['present', 'now', 'currently'],
                'visual_cues' => ['soft_focus', 'different_color_grade'],
                'recommended_pacing' => 'slow',
                'min_shots' => 2,
                'max_shots' => 8,
                'typical_shot_duration' => 6,
                'transition_rules' => ['soft_transition' => true, 'visual_cue' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'slow-drift', 'soft-focus'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 50,
                'priority' => 60,
            ],
            [
                'slug' => 'dream-sequence',
                'name' => 'Dream Sequence',
                'scene_type' => 'dream',
                'description' => 'Surreal dream coverage. Non-linear, unusual angles, fluid transitions.',
                'shot_sequence' => ['close-up', 'extreme-wide', 'dutch-angle', 'close-up', 'wide'],
                'detection_keywords' => ['dreams', 'nightmare', 'sleeping', 'surreal', 'imagines', 'vision', 'hallucination'],
                'negative_keywords' => ['awake', 'reality', 'real'],
                'visual_cues' => ['surreal_elements', 'unusual_lighting', 'distortion'],
                'recommended_pacing' => 'dynamic',
                'min_shots' => 3,
                'max_shots' => 10,
                'typical_shot_duration' => 5,
                'transition_rules' => ['non_linear' => true, 'morphs_allowed' => true],
                'default_movement_intensity' => 'dynamic',
                'preferred_movements' => ['floating', 'spiral', 'distort', 'slow-motion'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 51,
                'priority' => 55,
            ],
            [
                'slug' => 'interview-documentary',
                'name' => 'Interview/Documentary',
                'scene_type' => 'interview',
                'description' => 'Documentary-style interview coverage. Talking head with cutaways.',
                'shot_sequence' => ['medium', 'close-up', 'cutaway', 'medium', 'insert'],
                'detection_keywords' => ['interview', 'documentary', 'explains', 'narrates', 'recounts', 'testifies'],
                'negative_keywords' => ['fiction', 'story'],
                'visual_cues' => ['single_subject', 'plain_background', 'direct_address'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 2,
                'max_shots' => 8,
                'typical_shot_duration' => 10,
                'transition_rules' => ['jump_cuts_acceptable' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'slow-push-in'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 60,
                'priority' => 65,
            ],
            [
                'slug' => 'transition-standard',
                'name' => 'Scene Transition',
                'scene_type' => 'transition',
                'description' => 'Bridge between major scenes. Short establishing shots to reset context.',
                'shot_sequence' => ['wide', 'medium'],
                'detection_keywords' => ['meanwhile', 'elsewhere', 'cut to', 'transition'],
                'negative_keywords' => [],
                'visual_cues' => ['new_location', 'time_skip'],
                'recommended_pacing' => 'balanced',
                'min_shots' => 1,
                'max_shots' => 3,
                'typical_shot_duration' => 4,
                'transition_rules' => ['brief_shots' => true],
                'default_movement_intensity' => 'subtle',
                'preferred_movements' => ['static', 'pan'],
                'is_active' => true,
                'is_system' => true,
                'sort_order' => 70,
                'priority' => 50,
            ],
        ];

        foreach ($patterns as $pattern) {
            VwCoveragePattern::updateOrCreate(
                ['slug' => $pattern['slug']],
                $pattern
            );
        }

        VwCoveragePattern::clearCache();
    }
}
