<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwEmotionalBeat;

class VwEmotionalBeatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Emotional beats based on MasterClass Three-Act Structure and professional screenwriting.
     */
    public function run(): void
    {
        $beats = [
            // ===== ACT 1: SETUP (25%) =====
            [
                'slug' => 'hook',
                'name' => 'Hook',
                'description' => 'Attention-grabbing opening moment that captures viewer interest immediately',
                'story_position' => 'act1_setup',
                'intensity_level' => 7,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'vibrant',
                'recommended_shot_types' => json_encode(['establishing', 'wide', 'aerial', 'close-up']),
                'recommended_camera_movements' => json_encode(['crane', 'dolly', 'slow-reveal']),
                'recommended_lenses' => json_encode(['24mm', '35mm', '50mm']),
                'atmosphere_keywords' => 'attention-grabbing, intriguing, mysterious, compelling, immediate impact',
                'sort_order' => 1,
            ],
            [
                'slug' => 'introduction',
                'name' => 'Introduction',
                'description' => 'Character and world establishment, showing the ordinary world',
                'story_position' => 'act1_setup',
                'intensity_level' => 3,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'warm',
                'recommended_shot_types' => json_encode(['wide', 'medium', 'tracking', 'establishing']),
                'recommended_camera_movements' => json_encode(['slow-pan', 'gentle-tracking', 'observational']),
                'recommended_lenses' => json_encode(['35mm', '50mm']),
                'atmosphere_keywords' => 'everyday, normal, establishing, comfortable, familiar',
                'sort_order' => 2,
            ],
            [
                'slug' => 'normalcy',
                'name' => 'Normalcy',
                'description' => 'Everyday life before disruption, establishing the status quo',
                'story_position' => 'act1_setup',
                'intensity_level' => 2,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'neutral',
                'recommended_shot_types' => json_encode(['medium', 'wide', 'master']),
                'recommended_camera_movements' => json_encode(['static', 'subtle-drift', 'observational']),
                'recommended_lenses' => json_encode(['50mm', '35mm']),
                'atmosphere_keywords' => 'routine, ordinary, peaceful, baseline, calm before storm',
                'sort_order' => 3,
            ],
            [
                'slug' => 'inciting-incident',
                'name' => 'Inciting Incident',
                'description' => 'The event that disrupts the ordinary world and starts the story',
                'story_position' => 'act1_catalyst',
                'intensity_level' => 8,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'contrasting',
                'recommended_shot_types' => json_encode(['close-up', 'reaction', 'dolly', 'dutch-angle']),
                'recommended_camera_movements' => json_encode(['push-in', 'sudden-movement', 'reactive']),
                'recommended_lenses' => json_encode(['50mm', '85mm']),
                'atmosphere_keywords' => 'disruption, change, catalyst, unexpected, pivotal moment',
                'sort_order' => 4,
            ],
            [
                'slug' => 'refusal',
                'name' => 'Refusal of Call',
                'description' => 'Initial resistance to change, hesitation before commitment',
                'story_position' => 'act1_catalyst',
                'intensity_level' => 5,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'muted',
                'recommended_shot_types' => json_encode(['medium', 'over-shoulder', 'close-up']),
                'recommended_camera_movements' => json_encode(['static', 'slow-drift', 'contemplative']),
                'recommended_lenses' => json_encode(['50mm', '75mm']),
                'atmosphere_keywords' => 'hesitation, doubt, resistance, internal conflict, fear',
                'sort_order' => 5,
            ],
            [
                'slug' => 'acceptance',
                'name' => 'Acceptance',
                'description' => 'Commitment to the journey, crossing the threshold',
                'story_position' => 'act1_catalyst',
                'intensity_level' => 6,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'brightening',
                'recommended_shot_types' => json_encode(['medium-close', 'low-angle', 'dolly']),
                'recommended_camera_movements' => json_encode(['push-in', 'rising', 'forward-momentum']),
                'recommended_lenses' => json_encode(['35mm', '50mm']),
                'atmosphere_keywords' => 'determination, resolve, commitment, threshold, decision',
                'sort_order' => 6,
            ],

            // ===== ACT 2: CONFRONTATION (50%) =====
            [
                'slug' => 'exploration',
                'name' => 'Exploration',
                'description' => 'Discovering the new world or situation, learning the rules',
                'story_position' => 'act2_rising',
                'intensity_level' => 4,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'varied',
                'recommended_shot_types' => json_encode(['wide', 'tracking', 'pov', 'steadicam']),
                'recommended_camera_movements' => json_encode(['exploring', 'following', 'discovering']),
                'recommended_lenses' => json_encode(['24mm', '35mm']),
                'atmosphere_keywords' => 'discovery, wonder, learning, new territory, curiosity',
                'sort_order' => 10,
            ],
            [
                'slug' => 'fun-games',
                'name' => 'Fun and Games',
                'description' => 'Promise of premise delivered, the entertaining core of the story',
                'story_position' => 'act2_rising',
                'intensity_level' => 6,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'vibrant',
                'recommended_shot_types' => json_encode(['various', 'dynamic', 'medium', 'wide']),
                'recommended_camera_movements' => json_encode(['dynamic', 'energetic', 'montage-style']),
                'recommended_lenses' => json_encode(['35mm', '50mm', '24mm']),
                'atmosphere_keywords' => 'exciting, entertaining, promise of premise, momentum, energy',
                'sort_order' => 11,
            ],
            [
                'slug' => 'ally-enemy',
                'name' => 'Allies & Enemies',
                'description' => 'Relationship establishment, meeting helpers and obstacles',
                'story_position' => 'act2_rising',
                'intensity_level' => 5,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'character-specific',
                'recommended_shot_types' => json_encode(['two-shot', 'over-shoulder', 'reaction', 'medium']),
                'recommended_camera_movements' => json_encode(['conversational', 'reactive', 'character-focused']),
                'recommended_lenses' => json_encode(['50mm', '85mm']),
                'atmosphere_keywords' => 'bonding, conflict, relationship, trust, suspicion',
                'sort_order' => 12,
            ],
            [
                'slug' => 'first-challenge',
                'name' => 'First Challenge',
                'description' => 'Initial obstacle faced, testing the protagonist',
                'story_position' => 'act2_rising',
                'intensity_level' => 7,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'tense',
                'recommended_shot_types' => json_encode(['medium', 'handheld', 'close-up', 'reaction']),
                'recommended_camera_movements' => json_encode(['urgent', 'reactive', 'dynamic']),
                'recommended_lenses' => json_encode(['35mm', '50mm']),
                'atmosphere_keywords' => 'challenge, obstacle, testing, struggle, effort',
                'sort_order' => 13,
            ],
            [
                'slug' => 'midpoint-twist',
                'name' => 'Midpoint Twist',
                'description' => 'Major revelation or shift that changes everything',
                'story_position' => 'act2_midpoint',
                'intensity_level' => 9,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'dramatic-shift',
                'recommended_shot_types' => json_encode(['close-up', 'dolly-zoom', 'dutch-angle', 'reaction']),
                'recommended_camera_movements' => json_encode(['dramatic-push', 'vertigo-effect', 'revealing']),
                'recommended_lenses' => json_encode(['50mm', '85mm', 'zoom']),
                'atmosphere_keywords' => 'revelation, twist, game-changer, shocking, pivotal',
                'sort_order' => 14,
            ],
            [
                'slug' => 'stakes-raised',
                'name' => 'Stakes Raised',
                'description' => 'Consequences become real, the danger intensifies',
                'story_position' => 'act2_midpoint',
                'intensity_level' => 8,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'intense',
                'recommended_shot_types' => json_encode(['close-up', 'low-angle', 'wide', 'insert']),
                'recommended_camera_movements' => json_encode(['intense', 'focused', 'building']),
                'recommended_lenses' => json_encode(['50mm', '85mm', '35mm']),
                'atmosphere_keywords' => 'danger, consequences, urgency, pressure, escalation',
                'sort_order' => 15,
            ],
            [
                'slug' => 'all-is-lost',
                'name' => 'All Is Lost',
                'description' => 'Lowest point where hope fades, apparent defeat',
                'story_position' => 'act2_crisis',
                'intensity_level' => 9,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'desaturated',
                'recommended_shot_types' => json_encode(['high-angle', 'wide', 'close-up', 'static']),
                'recommended_camera_movements' => json_encode(['static', 'slow-retreat', 'distant']),
                'recommended_lenses' => json_encode(['35mm', '24mm', '85mm']),
                'atmosphere_keywords' => 'defeat, despair, hopeless, lowest point, devastation',
                'sort_order' => 16,
            ],
            [
                'slug' => 'dark-moment',
                'name' => 'Dark Night of Soul',
                'description' => 'Internal reckoning, confronting deepest fears',
                'story_position' => 'act2_crisis',
                'intensity_level' => 8,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'dark',
                'recommended_shot_types' => json_encode(['close-up', 'static', 'extreme-close-up']),
                'recommended_camera_movements' => json_encode(['static', 'intimate', 'contemplative']),
                'recommended_lenses' => json_encode(['85mm', '100mm']),
                'atmosphere_keywords' => 'introspection, darkness, inner conflict, doubt, soul-searching',
                'sort_order' => 17,
            ],

            // ===== ACT 3: RESOLUTION (25%) =====
            [
                'slug' => 'realization',
                'name' => 'Realization',
                'description' => 'Key insight discovered, the answer becomes clear',
                'story_position' => 'act3_climax',
                'intensity_level' => 7,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'dawning',
                'recommended_shot_types' => json_encode(['close-up', 'rack-focus', 'dolly', 'reaction']),
                'recommended_camera_movements' => json_encode(['push-in', 'revealing', 'dawning']),
                'recommended_lenses' => json_encode(['50mm', '85mm']),
                'atmosphere_keywords' => 'epiphany, clarity, understanding, breakthrough, insight',
                'sort_order' => 20,
            ],
            [
                'slug' => 'gathering-forces',
                'name' => 'Gathering Forces',
                'description' => 'Preparing for final confrontation, rallying resources',
                'story_position' => 'act3_climax',
                'intensity_level' => 6,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'building',
                'recommended_shot_types' => json_encode(['montage', 'tracking', 'wide', 'various']),
                'recommended_camera_movements' => json_encode(['dynamic', 'building-momentum', 'purposeful']),
                'recommended_lenses' => json_encode(['35mm', '50mm', '24mm']),
                'atmosphere_keywords' => 'preparation, determination, gathering, momentum, purpose',
                'sort_order' => 21,
            ],
            [
                'slug' => 'climax',
                'name' => 'Climax',
                'description' => 'Peak confrontation or action, the ultimate test',
                'story_position' => 'act3_climax',
                'intensity_level' => 10,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'intense',
                'recommended_shot_types' => json_encode(['dynamic', 'handheld', 'close-up', 'wide']),
                'recommended_camera_movements' => json_encode(['intense', 'dynamic', 'fast-cuts', 'visceral']),
                'recommended_lenses' => json_encode(['35mm', '50mm', '24mm']),
                'atmosphere_keywords' => 'peak action, confrontation, ultimate test, intense, maximum stakes',
                'sort_order' => 22,
            ],
            [
                'slug' => 'resolution',
                'name' => 'Resolution',
                'description' => 'Conflict resolved, consequences revealed',
                'story_position' => 'act3_resolution',
                'intensity_level' => 5,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'relieving',
                'recommended_shot_types' => json_encode(['medium', 'wide', 'two-shot', 'reaction']),
                'recommended_camera_movements' => json_encode(['slow', 'peaceful', 'settling']),
                'recommended_lenses' => json_encode(['50mm', '35mm']),
                'atmosphere_keywords' => 'resolution, relief, conclusion, aftermath, settling',
                'sort_order' => 23,
            ],
            [
                'slug' => 'new-normal',
                'name' => 'New Normal',
                'description' => 'Changed world after transformation, showing growth',
                'story_position' => 'act3_resolution',
                'intensity_level' => 3,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'warm',
                'recommended_shot_types' => json_encode(['wide', 'establishing', 'medium']),
                'recommended_camera_movements' => json_encode(['gentle', 'peaceful', 'reflective']),
                'recommended_lenses' => json_encode(['35mm', '50mm']),
                'atmosphere_keywords' => 'changed, growth, new beginning, transformed, peaceful',
                'sort_order' => 24,
            ],
            [
                'slug' => 'final-image',
                'name' => 'Final Image',
                'description' => 'Closing shot that echoes or contrasts opening, thematic completion',
                'story_position' => 'act3_resolution',
                'intensity_level' => 4,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'resonant',
                'recommended_shot_types' => json_encode(['wide', 'establishing', 'symbolic']),
                'recommended_camera_movements' => json_encode(['slow-pull-back', 'crane-up', 'fading']),
                'recommended_lenses' => json_encode(['35mm', '24mm', '50mm']),
                'atmosphere_keywords' => 'bookend, completion, resonance, final statement, thematic',
                'sort_order' => 25,
            ],

            // ===== STANDALONE EMOTIONAL BEATS =====
            [
                'slug' => 'tension',
                'name' => 'Tension',
                'description' => 'Building suspense or anxiety, keeping audience on edge',
                'story_position' => 'standalone',
                'intensity_level' => 7,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'cold',
                'recommended_shot_types' => json_encode(['close-up', 'dutch-angle', 'static', 'slow-push']),
                'recommended_camera_movements' => json_encode(['slow-creep', 'static-then-move', 'building']),
                'recommended_lenses' => json_encode(['50mm', '85mm', '35mm']),
                'atmosphere_keywords' => 'suspense, anxiety, unease, anticipation, dread',
                'sort_order' => 30,
            ],
            [
                'slug' => 'release',
                'name' => 'Release',
                'description' => 'Tension breaks, providing relief or payoff',
                'story_position' => 'standalone',
                'intensity_level' => 5,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'warming',
                'recommended_shot_types' => json_encode(['wide', 'medium', 'pull-back']),
                'recommended_camera_movements' => json_encode(['pull-back', 'exhale', 'relaxing']),
                'recommended_lenses' => json_encode(['35mm', '50mm']),
                'atmosphere_keywords' => 'relief, exhale, release, catharsis, breathing room',
                'sort_order' => 31,
            ],
            [
                'slug' => 'humor',
                'name' => 'Humor',
                'description' => 'Comic moment providing levity or relief',
                'story_position' => 'standalone',
                'intensity_level' => 4,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'bright',
                'recommended_shot_types' => json_encode(['medium', 'reaction', 'two-shot']),
                'recommended_camera_movements' => json_encode(['timing-focused', 'reactive', 'comedic-timing']),
                'recommended_lenses' => json_encode(['50mm', '35mm']),
                'atmosphere_keywords' => 'funny, light, comedic, witty, levity',
                'sort_order' => 32,
            ],
            [
                'slug' => 'romance',
                'name' => 'Romance',
                'description' => 'Intimate connection moment between characters',
                'story_position' => 'standalone',
                'intensity_level' => 5,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'warm-soft',
                'recommended_shot_types' => json_encode(['close-up', 'two-shot', 'shallow-focus']),
                'recommended_camera_movements' => json_encode(['gentle', 'intimate', 'soft']),
                'recommended_lenses' => json_encode(['85mm', '100mm', '50mm']),
                'atmosphere_keywords' => 'intimate, tender, romantic, connection, love',
                'sort_order' => 33,
            ],
            [
                'slug' => 'action',
                'name' => 'Action',
                'description' => 'Physical activity, conflict, or dynamic movement',
                'story_position' => 'standalone',
                'intensity_level' => 8,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'saturated',
                'recommended_shot_types' => json_encode(['wide', 'tracking', 'handheld', 'whip-pan']),
                'recommended_camera_movements' => json_encode(['dynamic', 'fast', 'following', 'visceral']),
                'recommended_lenses' => json_encode(['24mm', '35mm', '50mm']),
                'atmosphere_keywords' => 'dynamic, energetic, fast, physical, exciting',
                'sort_order' => 34,
            ],
            [
                'slug' => 'mystery',
                'name' => 'Mystery',
                'description' => 'Intrigue or unknown being explored or revealed',
                'story_position' => 'standalone',
                'intensity_level' => 6,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'shadows',
                'recommended_shot_types' => json_encode(['detail', 'rack-focus', 'shadow', 'pov']),
                'recommended_camera_movements' => json_encode(['slow-reveal', 'searching', 'mysterious']),
                'recommended_lenses' => json_encode(['50mm', '85mm', '35mm']),
                'atmosphere_keywords' => 'mysterious, intriguing, hidden, shadowy, unknown',
                'sort_order' => 35,
            ],
            [
                'slug' => 'triumph',
                'name' => 'Triumph',
                'description' => 'Victory, achievement, or success moment',
                'story_position' => 'standalone',
                'intensity_level' => 9,
                'pacing_suggestion' => 'medium',
                'color_mood' => 'golden',
                'recommended_shot_types' => json_encode(['low-angle', 'crane', 'wide', 'slow-motion']),
                'recommended_camera_movements' => json_encode(['rising', 'triumphant', 'epic']),
                'recommended_lenses' => json_encode(['24mm', '35mm', '50mm']),
                'atmosphere_keywords' => 'victory, success, triumphant, epic, heroic',
                'sort_order' => 36,
            ],
            [
                'slug' => 'tragedy',
                'name' => 'Tragedy',
                'description' => 'Loss, devastation, or deeply sad moment',
                'story_position' => 'standalone',
                'intensity_level' => 9,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'desaturated-cold',
                'recommended_shot_types' => json_encode(['high-angle', 'close-up', 'wide', 'static']),
                'recommended_camera_movements' => json_encode(['slow', 'heavy', 'weighted']),
                'recommended_lenses' => json_encode(['50mm', '85mm', '35mm']),
                'atmosphere_keywords' => 'loss, grief, devastating, sorrowful, tragic',
                'sort_order' => 37,
            ],
            [
                'slug' => 'wonder',
                'name' => 'Wonder',
                'description' => 'Awe-inspiring moment of discovery or beauty',
                'story_position' => 'standalone',
                'intensity_level' => 7,
                'pacing_suggestion' => 'slow',
                'color_mood' => 'magical',
                'recommended_shot_types' => json_encode(['wide', 'tilt', 'crane', 'slow-reveal']),
                'recommended_camera_movements' => json_encode(['slow-reveal', 'tilt-up', 'awe-inspired']),
                'recommended_lenses' => json_encode(['24mm', '16mm', '35mm']),
                'atmosphere_keywords' => 'awe, wonder, magical, beautiful, breathtaking',
                'sort_order' => 38,
            ],
            [
                'slug' => 'fear',
                'name' => 'Fear',
                'description' => 'Frightening or terrifying moment',
                'story_position' => 'standalone',
                'intensity_level' => 8,
                'pacing_suggestion' => 'fast',
                'color_mood' => 'dark-cold',
                'recommended_shot_types' => json_encode(['pov', 'dutch-angle', 'handheld', 'extreme-close-up']),
                'recommended_camera_movements' => json_encode(['chaotic', 'shaky', 'disorienting']),
                'recommended_lenses' => json_encode(['35mm', '24mm', '50mm']),
                'atmosphere_keywords' => 'terrifying, scary, dread, panic, horror',
                'sort_order' => 39,
            ],
        ];

        foreach ($beats as $beat) {
            VwEmotionalBeat::updateOrCreate(
                ['slug' => $beat['slug']],
                array_merge($beat, ['is_active' => true])
            );
        }
    }
}
