<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwGenrePreset;

class VwGenrePresetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Professional cinematography genre presets based on industry standards.
     * Includes primary genres (full cinematography specs) and modifier genres (blending traits).
     */
    public function run(): void
    {
        $presets = [
            // Documentary genres
            [
                'slug' => 'documentary-narrative',
                'name' => 'Documentary Narrative',
                'icon' => "\u{1F3AC}",
                'category' => 'documentary',
                'genre_type' => 'primary',
                'description' => 'Classic documentary storytelling with authentic visuals',
                'camera_language' => 'smooth tracking, wide establishing shots, intimate close-ups, observational framing',
                'color_grade' => 'natural tones, slight desaturation, documentary realism, authentic colors',
                'lighting' => 'natural light, available light, practical sources, soft ambient',
                'atmosphere' => 'authentic environments, real textures, genuine moments, unfiltered reality',
                'style' => 'documentary realism, authentic, observational, truthful storytelling',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 24mm lens',
                    'medium' => 'standard 35mm lens',
                    'close-up' => 'portrait 50mm lens',
                    'detail' => '85mm telephoto',
                ]),
                'sort_order' => 1,
            ],
            [
                'slug' => 'documentary-interview',
                'name' => 'Documentary Interview',
                'icon' => "\u{1F399}",
                'category' => 'documentary',
                'genre_type' => 'primary',
                'description' => 'Professional interview-style documentary',
                'camera_language' => 'static interviews, dramatic zooms, handheld urgency, eye-level framing',
                'color_grade' => 'neutral, clean whites, professional grade, natural skin tones',
                'lighting' => '3-point interview lighting, soft key light, subtle fill, separation rim',
                'atmosphere' => 'professional setting, clean backgrounds, focus on subject, minimal distractions',
                'style' => 'interview documentary, professional, clear, authoritative',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 35mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'portrait 85mm lens, shallow depth of field',
                ]),
                'sort_order' => 2,
            ],

            // Cinematic genres
            [
                'slug' => 'cinematic-thriller',
                'name' => 'Cinematic Thriller',
                'icon' => "\u{1F5E1}",
                'category' => 'cinematic',
                'genre_type' => 'primary',
                'description' => 'High-tension thriller with noir aesthetics',
                'camera_language' => 'slow dolly, low angles, stabilized gimbal, anamorphic lens feel, Dutch angles',
                'color_grade' => 'desaturated teal shadows, amber highlights, crushed blacks, high contrast',
                'lighting' => 'harsh single-source, dramatic rim lights, deep shadows, chiaroscuro',
                'atmosphere' => 'smoke, rain reflections, wet surfaces, urban grit, tension',
                'style' => 'ultra-cinematic photoreal, noir thriller, high contrast, Fincher-esque',
                'lens_preferences' => json_encode([
                    'establishing' => 'anamorphic 40mm lens',
                    'medium' => 'anamorphic 50mm lens',
                    'close-up' => 'anamorphic 75mm lens',
                    'detail' => 'macro lens, extreme detail',
                ]),
                'is_default' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'cinematic-action',
                'name' => 'Cinematic Action',
                'icon' => "\u{1F4A5}",
                'category' => 'cinematic',
                'genre_type' => 'primary',
                'description' => 'Blockbuster action with dynamic visuals',
                'camera_language' => 'fast dolly, Dutch angles, tracking shots, crash zooms, whip pans',
                'color_grade' => 'high contrast, orange and teal, saturated, punchy blacks',
                'lighting' => 'dramatic backlighting, lens flares, explosions, practical fire',
                'atmosphere' => 'dust, debris, fire, motion blur, chaos, energy',
                'style' => 'blockbuster action, high energy, dynamic composition, Michael Bay aesthetic',
                'lens_preferences' => json_encode([
                    'establishing' => 'ultra-wide 16mm lens',
                    'medium' => 'wide 24mm lens',
                    'close-up' => 'standard 50mm lens',
                ]),
                'sort_order' => 11,
            ],
            [
                'slug' => 'cinematic-drama',
                'name' => 'Cinematic Drama',
                'icon' => "\u{1F3AD}",
                'category' => 'cinematic',
                'genre_type' => 'primary',
                'description' => 'Prestige drama with emotional depth',
                'camera_language' => 'elegant slow movements, meaningful compositions, long takes, deliberate framing',
                'color_grade' => 'rich but restrained, natural skin tones, dramatic contrast, warm shadows',
                'lighting' => 'motivated lighting, golden hour, intimate practicals, soft natural light',
                'atmosphere' => 'subtle, realistic environments, emotional resonance, intimate spaces',
                'style' => 'prestige drama, Oscar-worthy cinematography, emotional depth, Deakins-inspired',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 32mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'portrait 85mm lens, f/1.4',
                ]),
                'sort_order' => 12,
            ],
            [
                'slug' => 'cinematic-epic',
                'name' => 'Cinematic Epic',
                'icon' => "\u{2694}",
                'category' => 'cinematic',
                'genre_type' => 'primary',
                'description' => 'Grand scale epic cinematography',
                'camera_language' => 'sweeping crane shots, helicopter aerials, massive scale, grand compositions',
                'color_grade' => 'rich saturated colors, golden highlights, deep shadows, majestic tones',
                'lighting' => 'natural dramatic light, god rays, sunset/sunrise, epic scale lighting',
                'atmosphere' => 'vast landscapes, armies, mountains, clouds, weather elements',
                'style' => 'epic grandeur, Lord of the Rings aesthetic, awe-inspiring, monumental',
                'lens_preferences' => json_encode([
                    'establishing' => 'ultra-wide 14mm lens',
                    'wide' => 'wide-angle 24mm lens',
                    'medium' => 'standard 50mm lens',
                ]),
                'sort_order' => 13,
            ],

            // Horror genres
            [
                'slug' => 'horror-psychological',
                'name' => 'Psychological Horror',
                'icon' => "\u{1F9E0}",
                'category' => 'horror',
                'genre_type' => 'primary',
                'description' => 'Unsettling psychological terror',
                'camera_language' => 'Dutch angles, slow creeping push-ins, unstable handheld, voyeuristic framing',
                'color_grade' => 'desaturated, sickly greens, deep blacks, red accents, unnatural tones',
                'lighting' => 'stark contrasts, flickering lights, deep shadows, underexposed areas',
                'atmosphere' => 'claustrophobic spaces, decay, isolation, dread, wrongness',
                'style' => 'psychological horror, Ari Aster style, unsettling, creeping dread',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 24mm with distortion',
                    'medium' => 'standard 35mm lens',
                    'close-up' => 'telephoto 100mm lens, isolating',
                ]),
                'sort_order' => 20,
            ],
            [
                'slug' => 'horror-supernatural',
                'name' => 'Supernatural Horror',
                'icon' => "\u{1F47B}",
                'category' => 'horror',
                'genre_type' => 'primary',
                'description' => 'Gothic supernatural horror aesthetics',
                'camera_language' => 'slow reveals, sudden movements, static then jarring, tracking through spaces',
                'color_grade' => 'cold blues, desaturated, crushed blacks, sickly highlights',
                'lighting' => 'practical candles, moonlight, shadows that move, minimal light sources',
                'atmosphere' => 'fog, mist, old buildings, supernatural elements, otherworldly',
                'style' => 'supernatural horror, James Wan aesthetic, gothic, terrifying',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 21mm lens',
                    'medium' => 'standard 40mm lens',
                    'close-up' => 'portrait 85mm lens',
                ]),
                'sort_order' => 21,
            ],

            // Comedy genres
            [
                'slug' => 'comedy-bright',
                'name' => 'Bright Comedy',
                'icon' => "\u{1F60A}",
                'category' => 'comedy',
                'genre_type' => 'primary',
                'description' => 'Light, colorful comedy aesthetics',
                'camera_language' => 'clean compositions, steady movement, reaction shots, comedic timing cuts',
                'color_grade' => 'bright, saturated, warm tones, cheerful palette, clean whites',
                'lighting' => 'soft even lighting, bright and airy, flattering, high key',
                'atmosphere' => 'colorful environments, clean spaces, inviting, fun',
                'style' => 'romantic comedy aesthetic, Wes Anderson lite, bright and cheerful',
                'lens_preferences' => json_encode([
                    'establishing' => 'standard 35mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'portrait 85mm lens',
                ]),
                'sort_order' => 30,
            ],
            [
                'slug' => 'comedy-dark',
                'name' => 'Dark Comedy',
                'icon' => "\u{1F921}",
                'category' => 'comedy',
                'genre_type' => 'primary',
                'description' => 'Sardonic dark comedy visuals',
                'camera_language' => 'deadpan framing, ironic compositions, uncomfortable holds, wide awkward shots',
                'color_grade' => 'muted colors, slight desaturation, ironic contrast, deliberate drabness',
                'lighting' => 'flat lighting with dramatic moments, practical sources, mundane',
                'atmosphere' => 'awkward spaces, mundane environments, ironic juxtaposition',
                'style' => 'dark comedy, Coen Brothers aesthetic, sardonic, uncomfortable humor',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 28mm lens',
                    'medium' => 'standard 40mm lens',
                    'close-up' => 'standard 50mm lens',
                ]),
                'sort_order' => 31,
            ],

            // Social/Commercial genres
            [
                'slug' => 'social-viral',
                'name' => 'Social Viral',
                'icon' => "\u{1F4F1}",
                'category' => 'social',
                'genre_type' => 'primary',
                'description' => 'TikTok/Reels optimized viral content',
                'camera_language' => 'dynamic handheld, quick cuts, POV shots, direct to camera, energetic movement',
                'color_grade' => 'vibrant, high contrast, punchy colors, social media optimized',
                'lighting' => 'ring light, natural bright light, clean and flattering',
                'atmosphere' => 'trendy, energetic, immediate, attention-grabbing',
                'style' => 'social media native, viral potential, scroll-stopping, engaging',
                'lens_preferences' => json_encode([
                    'establishing' => 'smartphone ultra-wide',
                    'medium' => 'standard 24mm lens',
                    'close-up' => 'standard 35mm lens',
                ]),
                'sort_order' => 40,
            ],
            [
                'slug' => 'commercial-premium',
                'name' => 'Premium Commercial',
                'icon' => "\u{2728}",
                'category' => 'commercial',
                'genre_type' => 'primary',
                'description' => 'High-end advertising cinematography',
                'camera_language' => 'smooth slider movements, turntable product shots, hero angles, precision framing',
                'color_grade' => 'clean, polished, brand-appropriate, premium feel, perfect exposure',
                'lighting' => 'professional studio lighting, product highlighting, controlled environment',
                'atmosphere' => 'aspirational, premium, desirable, perfect',
                'style' => 'Apple commercial aesthetic, premium advertising, polished perfection',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 35mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'macro lens for product detail',
                    'detail' => '100mm macro lens',
                ]),
                'sort_order' => 50,
            ],

            // Educational
            [
                'slug' => 'educational-explainer',
                'name' => 'Educational Explainer',
                'icon' => "\u{1F4DA}",
                'category' => 'educational',
                'genre_type' => 'primary',
                'description' => 'Clear educational content visuals',
                'camera_language' => 'clear framing, logical progression, presenter-focused, demonstrative angles',
                'color_grade' => 'clean, clear, good contrast, readable, accessible',
                'lighting' => 'even professional lighting, clear visibility, no harsh shadows',
                'atmosphere' => 'professional, trustworthy, clear, focused on learning',
                'style' => 'educational content, clear communication, professional explainer',
                'lens_preferences' => json_encode([
                    'establishing' => 'standard 35mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'standard 50mm lens',
                ]),
                'sort_order' => 60,
            ],

            // Experimental
            [
                'slug' => 'experimental-artistic',
                'name' => 'Experimental Artistic',
                'icon' => "\u{1F3A8}",
                'category' => 'experimental',
                'genre_type' => 'primary',
                'description' => 'Abstract artistic visual style',
                'camera_language' => 'unconventional angles, abstract framing, rule-breaking compositions, artistic movement',
                'color_grade' => 'stylized, bold choices, artistic interpretation, unique palette',
                'lighting' => 'dramatic, unconventional, artistic lighting choices, experimental',
                'atmosphere' => 'abstract, dreamlike, surreal, artistic expression',
                'style' => 'art house cinema, experimental, avant-garde, visually striking',
                'lens_preferences' => json_encode([
                    'establishing' => 'fisheye or ultra-wide',
                    'medium' => 'tilt-shift lens',
                    'close-up' => 'lensbaby or specialty lens',
                ]),
                'sort_order' => 70,
            ],

            // Standard fallback
            [
                'slug' => 'standard',
                'name' => 'Standard Cinematic',
                'icon' => "\u{1F3AC}",
                'category' => 'cinematic',
                'genre_type' => 'primary',
                'description' => 'Balanced professional cinematography',
                'camera_language' => 'smooth movements, balanced compositions, professional framing',
                'color_grade' => 'balanced, natural with cinematic punch, professional grade',
                'lighting' => 'professional three-point lighting, natural motivated sources',
                'atmosphere' => 'professional, polished, versatile',
                'style' => 'professional cinematography, balanced, versatile, high quality',
                'lens_preferences' => json_encode([
                    'establishing' => 'wide-angle 24mm lens',
                    'medium' => 'standard 50mm lens',
                    'close-up' => 'portrait 85mm lens',
                ]),
                'sort_order' => 100,
            ],
        ];

        foreach ($presets as $preset) {
            VwGenrePreset::updateOrCreate(
                ['slug' => $preset['slug']],
                array_merge($preset, ['is_active' => true])
            );
        }

        // Modifier genres - atomic single-concept genres that layer on top of primary genres
        $modifiers = [
            [
                'slug' => 'romance',
                'name' => 'Romance',
                'icon' => "\u{2764}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Romantic undertones with warm, intimate visual language',
                'camera_language' => 'intimate framing, soft focus pulls, gentle tracking, two-shots',
                'color_grade' => 'warm golden tones, soft contrast, rosy highlights',
                'lighting' => 'warm golden light, candlelit ambiance, soft diffused glow',
                'atmosphere' => 'intimate spaces, sunset hues, tender moments, gentle warmth',
                'style' => 'romantic visual language, intimate and tender',
                'blending_traits' => json_encode([
                    'camera' => 'intimate framing, soft focus transitions, gentle tracking movements',
                    'colorGrade' => 'warm golden undertones, soft rosy highlights',
                    'lighting' => 'warm golden light, soft diffused glow',
                    'atmosphere' => 'intimate warmth, tender emotional resonance',
                ]),
                'sort_order' => 200,
            ],
            [
                'slug' => 'mystery',
                'name' => 'Mystery',
                'icon' => "\u{1F50D}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Mysterious elements with selective reveals and tension',
                'camera_language' => 'selective framing, slow reveals, voyeuristic angles, hidden perspectives',
                'color_grade' => 'muted tones, deep shadows, selective color pops',
                'lighting' => 'selective pool lighting, shadows hiding details, strategic darkness',
                'atmosphere' => 'hidden corners, obscured details, unanswered questions',
                'style' => 'mystery visual language, selective and intriguing',
                'blending_traits' => json_encode([
                    'camera' => 'selective framing, slow reveals, voyeuristic angles',
                    'colorGrade' => 'deep shadow detail, muted selective tones',
                    'lighting' => 'selective pool lighting, strategic darkness',
                    'atmosphere' => 'hidden details, unanswered questions, intrigue',
                ]),
                'sort_order' => 201,
            ],
            [
                'slug' => 'sci-fi',
                'name' => 'Sci-Fi',
                'icon' => "\u{1F680}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Futuristic sci-fi elements with neon and technology',
                'camera_language' => 'symmetrical framing, tracking through corridors, scale reveals, clean geometry',
                'color_grade' => 'cool blue-teal palette, neon accents, holographic highlights',
                'lighting' => 'neon glow, holographic light sources, cool ambient LED',
                'atmosphere' => 'futuristic technology, clean surfaces, digital interfaces, vast scale',
                'style' => 'sci-fi visual language, futuristic and technological',
                'blending_traits' => json_encode([
                    'camera' => 'symmetrical framing, clean geometric compositions',
                    'colorGrade' => 'cool blue-teal accents, neon color pops',
                    'lighting' => 'neon glow, holographic light sources',
                    'atmosphere' => 'futuristic technology, digital interfaces, vast scale',
                ]),
                'sort_order' => 202,
            ],
            [
                'slug' => 'fantasy',
                'name' => 'Fantasy',
                'icon' => "\u{1F9D9}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Magical fantasy elements with ethereal beauty',
                'camera_language' => 'sweeping aerial movements, god-ray compositions, magical reveals',
                'color_grade' => 'rich saturated palette, golden ethereal glow, jewel tones',
                'lighting' => 'ethereal glow, god rays, magical light sources, bioluminescence',
                'atmosphere' => 'enchanted landscapes, mystical fog, magical particles, otherworldly beauty',
                'style' => 'fantasy visual language, magical and ethereal',
                'blending_traits' => json_encode([
                    'camera' => 'sweeping movements, magical reveal compositions',
                    'colorGrade' => 'golden ethereal glow, rich jewel tones',
                    'lighting' => 'ethereal glow, god rays, magical light sources',
                    'atmosphere' => 'mystical fog, magical particles, otherworldly beauty',
                ]),
                'sort_order' => 203,
            ],
            [
                'slug' => 'crime',
                'name' => 'Crime',
                'icon' => "\u{1F52B}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Gritty crime elements with urban tension',
                'camera_language' => 'handheld tension, surveillance framing, rooftop establishing shots',
                'color_grade' => 'desaturated urban palette, harsh fluorescent greens, sodium vapor yellows',
                'lighting' => 'harsh fluorescent, streetlight pools, neon bar signs',
                'atmosphere' => 'gritty streets, rain-slicked pavement, urban decay, back alleys',
                'style' => 'crime visual language, gritty and urban',
                'blending_traits' => json_encode([
                    'camera' => 'handheld tension, surveillance-style framing',
                    'colorGrade' => 'harsh fluorescent greens, sodium vapor yellows',
                    'lighting' => 'harsh fluorescent, streetlight pools',
                    'atmosphere' => 'gritty streets, rain-slicked pavement, urban tension',
                ]),
                'sort_order' => 204,
            ],
            [
                'slug' => 'supernatural',
                'name' => 'Supernatural',
                'icon' => "\u{1F47B}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Supernatural elements with uncanny distortions',
                'camera_language' => 'slow creeping movements, distorted perspectives, impossible angles',
                'color_grade' => 'shifted color spectrum, unnatural tones, otherworldly hues',
                'lighting' => 'flickering practical lights, impossible light sources, spectral glow',
                'atmosphere' => 'reality distortion, flickering between worlds, uncanny presence',
                'style' => 'supernatural visual language, uncanny and otherworldly',
                'blending_traits' => json_encode([
                    'camera' => 'slow creeping movements, distorted perspectives',
                    'colorGrade' => 'shifted spectrum, unnatural otherworldly tones',
                    'lighting' => 'flickering lights, spectral glow, impossible sources',
                    'atmosphere' => 'reality distortion, uncanny presence, between worlds',
                ]),
                'sort_order' => 205,
            ],
            [
                'slug' => 'action-modifier',
                'name' => 'Action',
                'icon' => "\u{1F4A5}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'High-energy action elements with kinetic movement',
                'camera_language' => 'fast tracking, crash zooms, impact framing, whip pans',
                'color_grade' => 'high contrast, saturated impact colors, orange-teal highlights',
                'lighting' => 'dramatic backlighting, explosion highlights, lens flares',
                'atmosphere' => 'dust and debris, motion blur, kinetic energy, impact',
                'style' => 'action visual language, high energy and kinetic',
                'blending_traits' => json_encode([
                    'camera' => 'fast tracking, crash zooms, kinetic whip pans',
                    'colorGrade' => 'high contrast impact, orange-teal accent highlights',
                    'lighting' => 'dramatic backlighting, explosion highlights',
                    'atmosphere' => 'dust and debris, motion blur, kinetic energy',
                ]),
                'sort_order' => 206,
            ],
            [
                'slug' => 'drama-modifier',
                'name' => 'Drama',
                'icon' => "\u{1F3AD}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Dramatic emotional elements with intimate depth',
                'camera_language' => 'long takes, intimate close-ups, motivated movement, meaningful compositions',
                'color_grade' => 'restrained naturalism, warm shadows, emotional color shifts',
                'lighting' => 'motivated light, intimate practicals, emotional window light',
                'atmosphere' => 'intimate spaces, emotional weight, quiet tension, meaningful silences',
                'style' => 'dramatic visual language, emotionally intimate',
                'blending_traits' => json_encode([
                    'camera' => 'long takes, intimate close-ups, meaningful compositions',
                    'colorGrade' => 'restrained naturalism, warm emotional shadows',
                    'lighting' => 'intimate motivated practicals, emotional window light',
                    'atmosphere' => 'emotional weight, meaningful silences, intimate depth',
                ]),
                'sort_order' => 207,
            ],
            [
                'slug' => 'thriller-modifier',
                'name' => 'Thriller',
                'icon' => "\u{1F630}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Thriller tension with claustrophobic pressure',
                'camera_language' => 'slow dolly push-ins, claustrophobic framing, over-shoulder tension',
                'color_grade' => 'desaturated, cold undertones, crushed shadow detail',
                'lighting' => 'harsh directional shadows, single-source pools, rim light isolation',
                'atmosphere' => 'claustrophobic tension, oppressive spaces, building dread',
                'style' => 'thriller visual language, tense and claustrophobic',
                'blending_traits' => json_encode([
                    'camera' => 'slow dolly push-ins, claustrophobic tight framing',
                    'colorGrade' => 'cold desaturated undertones, crushed shadows',
                    'lighting' => 'harsh directional shadows, isolating rim light',
                    'atmosphere' => 'claustrophobic tension, oppressive building dread',
                ]),
                'sort_order' => 208,
            ],
            [
                'slug' => 'comedy-modifier',
                'name' => 'Comedy',
                'icon' => "\u{1F604}",
                'category' => 'cinematic',
                'genre_type' => 'modifier',
                'description' => 'Comedic elements with bright, well-timed visuals',
                'camera_language' => 'well-timed reaction cuts, wide comedic framing, rhythmic editing',
                'color_grade' => 'bright and cheerful, high-key, warm saturated tones',
                'lighting' => 'bright even spaces, high-key lighting, flattering soft light',
                'atmosphere' => 'bright spaces, lively energy, playful timing, visual humor',
                'style' => 'comedic visual language, bright and well-timed',
                'blending_traits' => json_encode([
                    'camera' => 'well-timed reaction cuts, wide comedic framing',
                    'colorGrade' => 'bright cheerful tones, warm saturated highlights',
                    'lighting' => 'high-key brightness, flattering soft light',
                    'atmosphere' => 'lively energy, playful timing, visual humor',
                ]),
                'sort_order' => 209,
            ],
        ];

        foreach ($modifiers as $modifier) {
            VwGenrePreset::updateOrCreate(
                ['slug' => $modifier['slug']],
                array_merge($modifier, ['is_active' => true])
            );
        }
    }
}
