<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwSetting;

class VwSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // =============================================
            // SHOT INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'shot_intelligence_enabled',
                'name' => 'Enable AI Shot Intelligence',
                'category' => 'shot_intelligence',
                'description' => 'When enabled, AI will analyze each scene and dynamically determine the optimal number of shots, their types, and durations. When disabled, uses manual shot count selection.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'AI analyzes scene content (dialogue, action, emotion) to determine shot breakdown',
                'icon' => 'fa-solid fa-brain',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'shot_min_per_scene',
                'name' => 'Minimum Shots Per Scene',
                'category' => 'shot_intelligence',
                'description' => 'The minimum number of shots that can be created for any scene, regardless of AI recommendation.',
                'value_type' => 'integer',
                'value' => '1',
                'default_value' => '1',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Even simple scenes need at least this many shots',
                'icon' => 'fa-solid fa-arrow-down',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'shot_max_per_scene',
                'name' => 'Maximum Shots Per Scene',
                'category' => 'shot_intelligence',
                'description' => 'The maximum number of shots allowed per scene. Set higher for complex action sequences.',
                'value_type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'min_value' => 3,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Complex scenes with lots of action or dialogue may need more shots',
                'icon' => 'fa-solid fa-arrow-up',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'shot_default_count',
                'name' => 'Default Shot Count',
                'category' => 'shot_intelligence',
                'description' => 'Default number of shots when AI intelligence is disabled or as a fallback.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Used when manual mode is selected or AI cannot determine shot count',
                'icon' => 'fa-solid fa-hashtag',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'shot_ai_prompt',
                'name' => 'Shot Analysis AI Prompt',
                'category' => 'shot_intelligence',
                'description' => 'The prompt template used by AI to analyze scenes and determine shot breakdown. Variables: {{scene_description}}, {{narration}}, {{duration}}, {{mood}}, {{genre}}, {{pacing}}, {{has_dialogue}}, {{available_shot_types}}',
                'value_type' => 'string',
                'value' => 'Analyze this scene and determine the optimal cinematic shot breakdown.

SCENE: {{scene_description}}
NARRATION: {{narration}}
DURATION: {{duration}} seconds
MOOD: {{mood}}
GENRE: {{genre}}
PACING: {{pacing}}
HAS DIALOGUE: {{has_dialogue}}

DURATION RULES (CRITICAL - vary durations based on shot type and content):
- Establishing/Wide shots: 6s or 10s (longer to set the scene)
- Medium shots: 6s (standard narrative)
- Close-up shots: 5s (quick emotional impact)
- Detail/Insert shots: 5s (brief focus)
- Reaction shots: 5s (quick cut)
- Dialogue shots with lip-sync: 10s, 15s, or 20s (match dialogue length)
- Action sequences: 5s (fast pacing)
- Emotional/contemplative moments: 6s or 10s (let it breathe)

Consider:
1. Pacing - {{pacing}} pacing affects shot duration (fast=shorter, slow=longer)
2. Dialogue - shots with speaking characters need lip-sync (needsLipSync: true) and LONGER durations (10-20s)
3. Visual variety - mix shot types AND durations for professional look
4. Story beats - establish (6-10s), develop (5-6s), climax (5s for impact)
5. Scene mood - {{mood}} mood affects rhythm

Available shot types: {{available_shot_types}}

Return ONLY valid JSON (no markdown, no explanation):
{
  "shotCount": number,
  "reasoning": "brief explanation of shot and DURATION choices",
  "shots": [
    {
      "type": "shot_type_slug",
      "duration": number (MUST vary: 5 for close-ups/action, 6 for medium/standard, 10 for establishing/dialogue, 15-20 for long dialogue),
      "purpose": "why this shot",
      "cameraMovement": "movement description",
      "needsLipSync": boolean
    }
  ]
}',
                'default_value' => null,
                'input_type' => 'textarea',
                'input_help' => 'Customize how AI analyzes scenes. Use {{variables}} for dynamic content.',
                'icon' => 'fa-solid fa-message',
                'is_system' => true,
                'sort_order' => 5,
            ],

            // =============================================
            // ANIMATION MODEL SETTINGS
            // =============================================
            [
                'slug' => 'animation_default_model',
                'name' => 'Default Animation Model',
                'category' => 'animation',
                'description' => 'The default video animation model to use for standard shots.',
                'value_type' => 'string',
                'value' => 'minimax',
                'default_value' => 'minimax',
                'allowed_values' => ['minimax', 'multitalk'],
                'input_type' => 'select',
                'input_help' => 'MiniMax for general animation, Multitalk for lip-sync dialogue',
                'icon' => 'fa-solid fa-wand-magic-sparkles',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'animation_minimax_durations',
                'name' => 'MiniMax Duration Options',
                'category' => 'animation',
                'description' => 'Available duration options for MiniMax video generation (in seconds).',
                'value_type' => 'json',
                'value' => '[5, 6, 10]',
                'default_value' => '[5, 6, 10]',
                'input_type' => 'json_editor',
                'input_help' => 'Array of durations in seconds. MiniMax supports 5s, 6s, and 10s.',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'animation_minimax_default_duration',
                'name' => 'MiniMax Default Duration',
                'category' => 'animation',
                'description' => 'Default duration for MiniMax video generation.',
                'value_type' => 'integer',
                'value' => '6',
                'default_value' => '6',
                'allowed_values' => [5, 6, 10],
                'input_type' => 'select',
                'input_help' => 'Standard duration when not specified by AI or user',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'animation_multitalk_durations',
                'name' => 'Multitalk Duration Options',
                'category' => 'animation',
                'description' => 'Available duration options for Multitalk lip-sync video generation (in seconds).',
                'value_type' => 'json',
                'value' => '[5, 10, 15, 20]',
                'default_value' => '[5, 10, 15, 20]',
                'input_type' => 'json_editor',
                'input_help' => 'Array of durations in seconds. Multitalk supports longer durations for dialogue.',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'animation_multitalk_default_duration',
                'name' => 'Multitalk Default Duration',
                'category' => 'animation',
                'description' => 'Default duration for Multitalk lip-sync video generation.',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'allowed_values' => [5, 10, 15, 20],
                'input_type' => 'select',
                'input_help' => 'Standard duration for dialogue scenes',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'animation_auto_select_model',
                'name' => 'Auto-Select Model by Content',
                'category' => 'animation',
                'description' => 'Automatically select Multitalk for dialogue shots and MiniMax for others.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, shots with dialogue automatically use Multitalk if available',
                'icon' => 'fa-solid fa-robot',
                'is_system' => true,
                'sort_order' => 6,
            ],

            // =============================================
            // DURATION SETTINGS
            // =============================================
            [
                'slug' => 'duration_shot_min',
                'name' => 'Minimum Shot Duration',
                'category' => 'duration',
                'description' => 'Minimum duration for any individual shot (in seconds).',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Very short shots (under 3s) may feel too rushed',
                'icon' => 'fa-solid fa-hourglass-start',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'duration_shot_max',
                'name' => 'Maximum Shot Duration',
                'category' => 'duration',
                'description' => 'Maximum duration for any individual shot (in seconds).',
                'value_type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'min_value' => 5,
                'max_value' => 60,
                'input_type' => 'number',
                'input_help' => 'Long shots are supported by Multitalk for extended dialogue',
                'icon' => 'fa-solid fa-hourglass-end',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'duration_shot_default',
                'name' => 'Default Shot Duration',
                'category' => 'duration',
                'description' => 'Default duration when not specified by AI or user.',
                'value_type' => 'integer',
                'value' => '6',
                'default_value' => '6',
                'min_value' => 3,
                'max_value' => 20,
                'input_type' => 'number',
                'input_help' => '6 seconds is optimal for most shot types',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'duration_per_shot_enabled',
                'name' => 'Enable Per-Shot Duration',
                'category' => 'duration',
                'description' => 'Allow different durations for each shot within a scene (vs. uniform duration).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, each shot can have its own duration based on content',
                'icon' => 'fa-solid fa-sliders',
                'is_system' => true,
                'sort_order' => 4,
            ],

            // =============================================
            // SCENE PROCESSING SETTINGS
            // =============================================
            [
                'slug' => 'scene_duration_min',
                'name' => 'Minimum Scene Duration',
                'category' => 'scene',
                'description' => 'Minimum duration for any scene (in seconds).',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'min_value' => 5,
                'max_value' => 30,
                'input_type' => 'number',
                'input_help' => 'Scenes shorter than this may not have enough content',
                'icon' => 'fa-solid fa-minimize',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'scene_duration_max',
                'name' => 'Maximum Scene Duration',
                'category' => 'scene',
                'description' => 'Maximum duration for any scene (in seconds).',
                'value_type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'min_value' => 15,
                'max_value' => 300,
                'input_type' => 'number',
                'input_help' => 'Very long scenes should be split into multiple scenes',
                'icon' => 'fa-solid fa-maximize',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'scene_duration_default',
                'name' => 'Default Scene Duration',
                'category' => 'scene',
                'description' => 'Default duration when generating new scenes.',
                'value_type' => 'integer',
                'value' => '15',
                'default_value' => '15',
                'min_value' => 10,
                'max_value' => 60,
                'input_type' => 'number',
                'input_help' => '15 seconds provides good balance of content and pacing',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'scene_auto_decompose',
                'name' => 'Auto-Decompose Scenes',
                'category' => 'scene',
                'description' => 'Automatically decompose scenes into shots when entering animation phase.',
                'value_type' => 'boolean',
                'value' => 'false',
                'default_value' => 'false',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, all scenes are automatically decomposed without manual trigger',
                'icon' => 'fa-solid fa-wand-magic',
                'is_system' => true,
                'sort_order' => 4,
            ],

            // =============================================
            // GENERAL WIZARD SETTINGS
            // =============================================
            [
                'slug' => 'frame_chaining_enabled',
                'name' => 'Enable Frame Chaining',
                'category' => 'general',
                'description' => 'Use last frame of previous shot as starting frame for next shot (ensures visual continuity).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Recommended for professional-looking shot transitions',
                'icon' => 'fa-solid fa-link',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'style_bible_enforcement',
                'name' => 'Style Bible Enforcement Level',
                'category' => 'general',
                'description' => 'How strictly to apply Style Bible settings to generated content.',
                'value_type' => 'string',
                'value' => 'moderate',
                'default_value' => 'moderate',
                'allowed_values' => ['strict', 'moderate', 'loose'],
                'input_type' => 'select',
                'input_help' => 'Strict: exact match required, Moderate: balanced, Loose: general guidance',
                'icon' => 'fa-solid fa-palette',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'parallel_generation_limit',
                'name' => 'Parallel Generation Limit',
                'category' => 'general',
                'description' => 'Maximum number of shots/images to generate in parallel.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Higher values speed up generation but may hit API rate limits',
                'icon' => 'fa-solid fa-layer-group',
                'is_system' => true,
                'sort_order' => 3,
            ],

            // =============================================
            // API ENDPOINTS SETTINGS
            // =============================================
            [
                'slug' => 'api_runpod_key',
                'name' => 'RunPod API Key',
                'category' => 'api',
                'description' => 'API key for RunPod serverless endpoints (Multitalk, HiDream, etc.).',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'password',
                'input_help' => 'Get your API key from runpod.io dashboard',
                'icon' => 'fa-solid fa-key',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'api_runpod_multitalk_endpoint',
                'name' => 'RunPod Multitalk Endpoint',
                'category' => 'api',
                'description' => 'RunPod serverless endpoint URL for Multitalk lip-sync video generation.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Format: https://api.runpod.ai/v2/{endpoint_id}/run',
                'icon' => 'fa-solid fa-video',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'api_runpod_hidream_endpoint',
                'name' => 'RunPod HiDream Endpoint',
                'category' => 'api',
                'description' => 'RunPod serverless endpoint URL for HiDream image generation.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Format: https://api.runpod.ai/v2/{endpoint_id}/run',
                'icon' => 'fa-solid fa-image',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'api_minimax_key',
                'name' => 'MiniMax API Key',
                'category' => 'api',
                'description' => 'API key for MiniMax video generation service.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'password',
                'input_help' => 'Required for image-to-video animation',
                'icon' => 'fa-solid fa-key',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'api_minimax_group_id',
                'name' => 'MiniMax Group ID',
                'category' => 'api',
                'description' => 'Group ID for MiniMax API authentication.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Found in your MiniMax dashboard',
                'icon' => 'fa-solid fa-users',
                'is_system' => true,
                'sort_order' => 5,
            ],

            // =============================================
            // CREDIT COSTS SETTINGS
            // =============================================
            [
                'slug' => 'credits_script_generation',
                'name' => 'Script Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating a new script.',
                'value_type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost per script generation request',
                'icon' => 'fa-solid fa-scroll',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'credits_image_generation',
                'name' => 'Image Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating a single image.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per image generation',
                'icon' => 'fa-solid fa-image',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'credits_voiceover_generation',
                'name' => 'Voiceover Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating voiceover audio.',
                'value_type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per voiceover generation',
                'icon' => 'fa-solid fa-microphone',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'credits_video_animation',
                'name' => 'Video Animation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for animating a single shot/image.',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost per video animation (MiniMax or Multitalk)',
                'icon' => 'fa-solid fa-video',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'credits_video_export',
                'name' => 'Video Export Cost',
                'category' => 'credits',
                'description' => 'Credits charged for exporting final video.',
                'value_type' => 'integer',
                'value' => '15',
                'default_value' => '15',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost for final video rendering and export',
                'icon' => 'fa-solid fa-file-export',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'credits_concept_improvement',
                'name' => 'Concept Improvement Cost',
                'category' => 'credits',
                'description' => 'Credits charged for AI concept improvement.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per concept improvement request',
                'icon' => 'fa-solid fa-lightbulb',
                'is_system' => true,
                'sort_order' => 6,
            ],

            // =============================================
            // AI PROVIDER SETTINGS
            // =============================================
            [
                'slug' => 'ai_script_provider',
                'name' => 'Script Generation Provider',
                'category' => 'ai_providers',
                'description' => 'AI provider to use for script generation.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'grok', 'gemini', 'anthropic'],
                'input_type' => 'select',
                'input_help' => 'Select which AI provider generates scripts',
                'icon' => 'fa-solid fa-brain',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'ai_script_model',
                'name' => 'Script Generation Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for script generation.',
                'value_type' => 'string',
                'value' => 'gpt-4',
                'default_value' => 'gpt-4',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., gpt-4, gpt-4-turbo, claude-3-opus)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'ai_shot_analysis_provider',
                'name' => 'Shot Analysis Provider',
                'category' => 'ai_providers',
                'description' => 'AI provider to use for shot intelligence analysis.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'grok', 'gemini', 'anthropic'],
                'input_type' => 'select',
                'input_help' => 'Provider for AI shot decomposition analysis',
                'icon' => 'fa-solid fa-magnifying-glass-chart',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'ai_shot_analysis_model',
                'name' => 'Shot Analysis Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for shot intelligence analysis.',
                'value_type' => 'string',
                'value' => 'gpt-4',
                'default_value' => 'gpt-4',
                'input_type' => 'text',
                'input_help' => 'Recommend GPT-4 or Claude for complex scene analysis',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'ai_image_provider',
                'name' => 'Image Generation Provider',
                'category' => 'ai_providers',
                'description' => 'Default image generation provider.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'hidream', 'stability', 'midjourney'],
                'input_type' => 'select',
                'input_help' => 'OpenAI DALL-E, HiDream, Stability AI, etc.',
                'icon' => 'fa-solid fa-paintbrush',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'ai_image_model',
                'name' => 'Image Generation Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for image generation.',
                'value_type' => 'string',
                'value' => 'dall-e-3',
                'default_value' => 'dall-e-3',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., dall-e-3, hidream-i1-full)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'ai_voiceover_provider',
                'name' => 'Voiceover Provider',
                'category' => 'ai_providers',
                'description' => 'TTS provider for voiceover generation.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'elevenlabs', 'google'],
                'input_type' => 'select',
                'input_help' => 'Text-to-speech provider',
                'icon' => 'fa-solid fa-volume-high',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'ai_voiceover_model',
                'name' => 'Voiceover Model',
                'category' => 'ai_providers',
                'description' => 'TTS model for voiceover generation.',
                'value_type' => 'string',
                'value' => 'tts-1-hd',
                'default_value' => 'tts-1-hd',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., tts-1-hd, eleven_multilingual_v2)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 8,
            ],

            // =============================================
            // PRODUCTION INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'production_auto_multishot_types',
                'name' => 'Auto-Enable Multi-Shot for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Multi-Shot Mode. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial,music-video',
                'default_value' => 'movie,documentary,commercial,music-video',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary,commercial - these types auto-enable multi-shot decomposition',
                'icon' => 'fa-solid fa-film',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'production_auto_character_bible_types',
                'name' => 'Auto-Enable Character Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Character Bible detection. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial,narrative',
                'default_value' => 'movie,documentary,commercial,narrative',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary - these types auto-detect and track characters',
                'icon' => 'fa-solid fa-users',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'production_main_char_scene_percent',
                'name' => 'Main Character Scene Percentage',
                'category' => 'production_intelligence',
                'description' => 'Minimum percentage of scenes where Main characters should appear (cinematic continuity).',
                'value_type' => 'integer',
                'value' => '70',
                'default_value' => '70',
                'min_value' => 30,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Main characters will be expanded to appear in at least this % of scenes',
                'icon' => 'fa-solid fa-star',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'production_supporting_char_scene_percent',
                'name' => 'Supporting Character Scene Percentage',
                'category' => 'production_intelligence',
                'description' => 'Minimum percentage of scenes where Supporting characters should appear.',
                'value_type' => 'integer',
                'value' => '40',
                'default_value' => '40',
                'min_value' => 10,
                'max_value' => 80,
                'input_type' => 'number',
                'input_help' => 'Supporting characters will be expanded to appear in at least this % of scenes',
                'icon' => 'fa-solid fa-user-group',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'production_portrait_single_person',
                'name' => 'Enforce Single-Person Portraits',
                'category' => 'production_intelligence',
                'description' => 'When enabled, character portrait generation strictly enforces single-person output.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Adds strong single-person directives to portrait prompts',
                'icon' => 'fa-solid fa-portrait',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'production_auto_location_bible_types',
                'name' => 'Auto-Enable Location Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Location Bible detection. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial',
                'default_value' => 'movie,documentary,commercial',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary - these types auto-detect and track locations',
                'icon' => 'fa-solid fa-location-dot',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'production_auto_style_bible_types',
                'name' => 'Auto-Enable Style Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Style Bible. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,commercial,music-video',
                'default_value' => 'movie,commercial,music-video',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,commercial - these types auto-enable visual style consistency',
                'icon' => 'fa-solid fa-palette',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'production_narrative_tracking_types',
                'name' => 'Narrative Continuity Tracking Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that use narrative (not literal) character tracking. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,narrative',
                'default_value' => 'movie,documentary,narrative',
                'input_type' => 'text',
                'input_help' => 'Narrative tracking expands character presence based on story logic, not just mentions',
                'icon' => 'fa-solid fa-book-open',
                'is_system' => true,
                'sort_order' => 8,
            ],
        ];

        foreach ($settings as $setting) {
            VwSetting::updateOrCreate(
                ['slug' => $setting['slug']],
                $setting
            );
        }

        // Clear cache after seeding
        VwSetting::clearCache();
    }
}
