<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwSeedanceStyle;

class VwSeedanceStyleSeeder extends Seeder
{
    public function run(): void
    {
        $styles = [
            // ===== VISUAL STYLES (10) =====
            [
                'slug' => 'cinematic',
                'name' => 'Cinematic',
                'category' => 'visual',
                'description' => 'Classic cinema look with shallow depth of field and professional composition.',
                'prompt_syntax' => 'Cinematic, photorealistic',
                'compatible_genres' => json_encode(['drama', 'thriller', 'action', 'romance']),
                'compatible_moods' => json_encode(['dramatic', 'tense', 'romantic', 'epic']),
                'is_default' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'commercial',
                'name' => 'Commercial',
                'category' => 'visual',
                'description' => 'Bright, clean look optimized for advertising and product-focused content.',
                'prompt_syntax' => 'Clean commercial photography style, bright and polished',
                'compatible_genres' => json_encode(['commercial', 'lifestyle', 'product']),
                'compatible_moods' => json_encode(['upbeat', 'professional', 'clean', 'modern']),
                'sort_order' => 2,
            ],
            [
                'slug' => 'documentary',
                'name' => 'Documentary',
                'category' => 'visual',
                'description' => 'Natural, observational style with minimal stylization.',
                'prompt_syntax' => 'Documentary-style naturalistic photography',
                'compatible_genres' => json_encode(['documentary', 'drama', 'biography']),
                'compatible_moods' => json_encode(['authentic', 'intimate', 'raw', 'observational']),
                'sort_order' => 3,
            ],
            [
                'slug' => 'animated',
                'name' => 'Animated',
                'category' => 'visual',
                'description' => 'Stylized animation-inspired look with exaggerated colors and forms.',
                'prompt_syntax' => 'Stylized animated look, vibrant and expressive',
                'compatible_genres' => json_encode(['animation', 'fantasy', 'comedy']),
                'compatible_moods' => json_encode(['playful', 'whimsical', 'vibrant', 'fantastical']),
                'sort_order' => 4,
            ],
            [
                'slug' => 'whimsical',
                'name' => 'Whimsical',
                'category' => 'visual',
                'description' => 'Dreamy, fantastical visual quality with soft edges and magical atmosphere.',
                'prompt_syntax' => 'Whimsical, dreamlike visual quality with soft ethereal glow',
                'compatible_genres' => json_encode(['fantasy', 'children', 'romance']),
                'compatible_moods' => json_encode(['dreamy', 'magical', 'gentle', 'wonder']),
                'sort_order' => 5,
            ],
            [
                'slug' => 'timelapse',
                'name' => 'Timelapse',
                'category' => 'visual',
                'description' => 'Compressed time visual style showing passage of time.',
                'prompt_syntax' => 'Timelapse photography style, compressed motion over time',
                'compatible_genres' => json_encode(['documentary', 'nature', 'urban', 'science']),
                'compatible_moods' => json_encode(['contemplative', 'epic', 'meditative', 'transformative']),
                'sort_order' => 6,
            ],
            [
                'slug' => 'lifestyle',
                'name' => 'Lifestyle',
                'category' => 'visual',
                'description' => 'Warm, aspirational visual style for lifestyle and social content.',
                'prompt_syntax' => 'Warm lifestyle photography, aspirational and authentic',
                'compatible_genres' => json_encode(['lifestyle', 'social', 'wellness', 'travel']),
                'compatible_moods' => json_encode(['warm', 'inviting', 'authentic', 'aspirational']),
                'sort_order' => 7,
            ],
            [
                'slug' => 'futuristic',
                'name' => 'Futuristic',
                'category' => 'visual',
                'description' => 'Sci-fi inspired visuals with sleek surfaces and technological aesthetic.',
                'prompt_syntax' => 'Futuristic sci-fi visual style, sleek and technological',
                'compatible_genres' => json_encode(['sci-fi', 'tech', 'cyberpunk', 'futurism']),
                'compatible_moods' => json_encode(['futuristic', 'sleek', 'cold', 'advanced']),
                'sort_order' => 8,
            ],
            [
                'slug' => 'film-grain',
                'name' => 'Film Grain',
                'category' => 'visual',
                'description' => 'Analog film texture with organic grain and classic film characteristics.',
                'prompt_syntax' => 'Film grain texture, analog film stock look',
                'compatible_genres' => json_encode(['drama', 'indie', 'period', 'noir']),
                'compatible_moods' => json_encode(['nostalgic', 'gritty', 'authentic', 'vintage']),
                'sort_order' => 9,
            ],
            [
                'slug' => 'slow-motion',
                'name' => 'Slow Motion',
                'category' => 'visual',
                'description' => 'High-speed capture for dramatic slow-motion effect.',
                'prompt_syntax' => 'Slow-motion, high frame rate capture with fluid motion',
                'compatible_genres' => json_encode(['action', 'sports', 'drama', 'music-video']),
                'compatible_moods' => json_encode(['dramatic', 'intense', 'poetic', 'powerful']),
                'sort_order' => 10,
            ],

            // ===== LIGHTING STYLES (9) =====
            [
                'slug' => 'golden-hour',
                'name' => 'Golden Hour',
                'category' => 'lighting',
                'description' => 'Warm, soft directional light from low sun angle.',
                'prompt_syntax' => 'Golden hour warm sunlight with long soft shadows',
                'compatible_genres' => json_encode(['romance', 'drama', 'lifestyle', 'nature']),
                'compatible_moods' => json_encode(['warm', 'romantic', 'nostalgic', 'serene']),
                'is_default' => false,
                'sort_order' => 1,
            ],
            [
                'slug' => 'butterfly-lighting',
                'name' => 'Butterfly Lighting',
                'category' => 'lighting',
                'description' => 'Classic portrait lighting from above, creating butterfly shadow under nose.',
                'prompt_syntax' => 'Butterfly lighting from above, glamorous portrait illumination',
                'compatible_genres' => json_encode(['portrait', 'beauty', 'fashion', 'commercial']),
                'compatible_moods' => json_encode(['glamorous', 'elegant', 'polished', 'beautiful']),
                'sort_order' => 2,
            ],
            [
                'slug' => 'dramatic-top-lighting',
                'name' => 'Dramatic Top Lighting',
                'category' => 'lighting',
                'description' => 'Hard overhead light creating deep shadows and dramatic contrast.',
                'prompt_syntax' => 'Dramatic top-down lighting with deep shadows',
                'compatible_genres' => json_encode(['thriller', 'horror', 'drama', 'noir']),
                'compatible_moods' => json_encode(['ominous', 'dramatic', 'tense', 'sinister']),
                'sort_order' => 3,
            ],
            [
                'slug' => 'high-contrast',
                'name' => 'High Contrast',
                'category' => 'lighting',
                'description' => 'Strong light/dark separation with minimal fill.',
                'prompt_syntax' => 'High contrast lighting with strong shadows and bright highlights',
                'compatible_genres' => json_encode(['noir', 'thriller', 'action', 'drama']),
                'compatible_moods' => json_encode(['intense', 'bold', 'dramatic', 'powerful']),
                'sort_order' => 4,
            ],
            [
                'slug' => 'neon-lighting',
                'name' => 'Neon Lighting',
                'category' => 'lighting',
                'description' => 'Colorful neon-lit environment with vivid color spill.',
                'prompt_syntax' => 'Neon lighting with vivid color spill and reflections',
                'compatible_genres' => json_encode(['cyberpunk', 'sci-fi', 'music-video', 'urban']),
                'compatible_moods' => json_encode(['electric', 'vibrant', 'edgy', 'nocturnal']),
                'sort_order' => 5,
            ],
            [
                'slug' => 'fluorescent-lighting',
                'name' => 'Fluorescent Lighting',
                'category' => 'lighting',
                'description' => 'Cool, flat institutional fluorescent lights for clinical atmosphere.',
                'prompt_syntax' => 'Cool fluorescent overhead lighting, flat and clinical',
                'compatible_genres' => json_encode(['thriller', 'horror', 'drama', 'documentary']),
                'compatible_moods' => json_encode(['sterile', 'uncomfortable', 'institutional', 'unsettling']),
                'sort_order' => 6,
            ],
            [
                'slug' => 'backlighting',
                'name' => 'Backlighting',
                'category' => 'lighting',
                'description' => 'Subject lit from behind creating rim light and silhouette edge.',
                'prompt_syntax' => 'Backlit with rim lighting and glowing edge separation',
                'compatible_genres' => json_encode(['drama', 'romance', 'music-video', 'fashion']),
                'compatible_moods' => json_encode(['ethereal', 'angelic', 'mysterious', 'dramatic']),
                'sort_order' => 7,
            ],
            [
                'slug' => 'natural-window-light',
                'name' => 'Natural Window Light',
                'category' => 'lighting',
                'description' => 'Soft, diffused natural light from a window source.',
                'prompt_syntax' => 'Soft natural window light with gentle diffusion',
                'compatible_genres' => json_encode(['drama', 'romance', 'lifestyle', 'indie']),
                'compatible_moods' => json_encode(['natural', 'intimate', 'calm', 'genuine']),
                'is_default' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'shallow-depth-of-field',
                'name' => 'Shallow Depth of Field',
                'category' => 'lighting',
                'description' => 'Strong background blur isolating subject with bokeh.',
                'prompt_syntax' => 'Shallow depth of field with creamy bokeh background',
                'compatible_genres' => json_encode(['portrait', 'drama', 'romance', 'fashion']),
                'compatible_moods' => json_encode(['intimate', 'focused', 'dreamy', 'personal']),
                'sort_order' => 9,
            ],

            // ===== COLOR TREATMENTS (7) =====
            [
                'slug' => 'teal-and-orange',
                'name' => 'Teal and Orange',
                'category' => 'color',
                'description' => 'Classic Hollywood color grading with teal shadows and orange highlights.',
                'prompt_syntax' => 'Teal-and-orange cinematic color grading',
                'compatible_genres' => json_encode(['action', 'thriller', 'drama', 'sci-fi']),
                'compatible_moods' => json_encode(['cinematic', 'dramatic', 'bold', 'blockbuster']),
                'sort_order' => 1,
            ],
            [
                'slug' => 'yellow-green-tint',
                'name' => 'Yellow-Green Tint',
                'category' => 'color',
                'description' => 'Muted yellow-green color cast for institutional or uneasy feel.',
                'prompt_syntax' => 'Yellow-green color tint, muted and uneasy palette',
                'compatible_genres' => json_encode(['thriller', 'horror', 'drama', 'war']),
                'compatible_moods' => json_encode(['uneasy', 'sickly', 'oppressive', 'dystopian']),
                'sort_order' => 2,
            ],
            [
                'slug' => 'hyper-realistic-detail',
                'name' => 'Hyper-Realistic Detail',
                'category' => 'color',
                'description' => 'Enhanced detail and texture with vivid, true-to-life color accuracy.',
                'prompt_syntax' => 'Hyper-realistic detail, razor-sharp textures with vivid natural colors',
                'compatible_genres' => json_encode(['nature', 'documentary', 'product', 'food']),
                'compatible_moods' => json_encode(['vivid', 'detailed', 'lifelike', 'precise']),
                'sort_order' => 3,
            ],
            [
                'slug' => 'retro-grain',
                'name' => 'Retro Grain',
                'category' => 'color',
                'description' => 'Vintage color treatment with faded tones and analog grain.',
                'prompt_syntax' => 'Retro film grain with faded vintage color palette',
                'compatible_genres' => json_encode(['indie', 'period', 'drama', 'music-video']),
                'compatible_moods' => json_encode(['nostalgic', 'vintage', 'melancholic', 'warm']),
                'sort_order' => 4,
            ],
            [
                'slug' => 'step-printing',
                'name' => 'Step Printing',
                'category' => 'color',
                'description' => 'Film step-printing effect with duplicated frames and stutter motion.',
                'prompt_syntax' => 'Step-printing effect with stuttered frame repetition',
                'compatible_genres' => json_encode(['action', 'horror', 'experimental', 'music-video']),
                'compatible_moods' => json_encode(['frenetic', 'chaotic', 'intense', 'disorienting']),
                'sort_order' => 5,
            ],
            [
                'slug' => 'hdr',
                'name' => 'HDR',
                'category' => 'color',
                'description' => 'High dynamic range with expanded highlight and shadow detail.',
                'prompt_syntax' => 'HDR high dynamic range with expanded tonal detail',
                'compatible_genres' => json_encode(['nature', 'landscape', 'architecture', 'commercial']),
                'compatible_moods' => json_encode(['vivid', 'expansive', 'rich', 'detailed']),
                'sort_order' => 6,
            ],
            [
                'slug' => 'film-noir',
                'name' => 'Film Noir',
                'category' => 'color',
                'description' => 'High-contrast black and white or desaturated look with dramatic shadows.',
                'prompt_syntax' => 'Film noir style, high-contrast desaturated with deep blacks',
                'compatible_genres' => json_encode(['noir', 'thriller', 'detective', 'drama']),
                'compatible_moods' => json_encode(['mysterious', 'dark', 'moody', 'brooding']),
                'sort_order' => 7,
            ],
        ];

        foreach ($styles as $style) {
            VwSeedanceStyle::updateOrCreate(
                ['slug' => $style['slug']],
                array_merge(['is_active' => true], $style)
            );
        }
    }
}
