<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwSetting;

class VwSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // =============================================
            // SHOT INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'shot_intelligence_enabled',
                'name' => 'Enable AI Shot Intelligence',
                'category' => 'shot_intelligence',
                'description' => 'When enabled, AI will analyze each scene and dynamically determine the optimal number of shots, their types, and durations. When disabled, uses manual shot count selection.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'AI analyzes scene content (dialogue, action, emotion) to determine shot breakdown',
                'icon' => 'fa-solid fa-brain',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'shot_min_per_scene',
                'name' => 'Minimum Shots Per Scene',
                'category' => 'shot_intelligence',
                'description' => 'The minimum number of shots that can be created for any scene, regardless of AI recommendation.',
                'value_type' => 'integer',
                'value' => '1',
                'default_value' => '1',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Even simple scenes need at least this many shots',
                'icon' => 'fa-solid fa-arrow-down',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'shot_max_per_scene',
                'name' => 'Maximum Shots Per Scene',
                'category' => 'shot_intelligence',
                'description' => 'The maximum number of shots allowed per scene. Set higher for complex action sequences.',
                'value_type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'min_value' => 3,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Complex scenes with lots of action or dialogue may need more shots',
                'icon' => 'fa-solid fa-arrow-up',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'shot_default_count',
                'name' => 'Default Shot Count',
                'category' => 'shot_intelligence',
                'description' => 'Default number of shots when AI intelligence is disabled or as a fallback.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Used when manual mode is selected or AI cannot determine shot count',
                'icon' => 'fa-solid fa-hashtag',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'shot_ai_prompt',
                'name' => 'Shot Analysis AI Prompt',
                'category' => 'shot_intelligence',
                'description' => 'The prompt template used by AI to analyze scenes and determine shot breakdown. Variables: {{scene_description}}, {{narration}}, {{duration}}, {{mood}}, {{genre}}, {{pacing}}, {{has_dialogue}}, {{available_shot_types}}',
                'value_type' => 'string',
                'value' => 'Analyze this scene and determine the optimal cinematic shot breakdown.

SCENE: {{scene_description}}
NARRATION: {{narration}}
DURATION: {{duration}} seconds
MOOD: {{mood}}
GENRE: {{genre}}
PACING: {{pacing}}
HAS DIALOGUE: {{has_dialogue}}

DURATION RULES (CRITICAL - vary durations based on shot type and content):
- Establishing/Wide shots: 6s or 10s (longer to set the scene)
- Medium shots: 6s (standard narrative)
- Close-up shots: 5s (quick emotional impact)
- Detail/Insert shots: 5s (brief focus)
- Reaction shots: 5s (quick cut)
- Dialogue shots with lip-sync: 10s, 15s, or 20s (match dialogue length)
- Action sequences: 5s (fast pacing)
- Emotional/contemplative moments: 6s or 10s (let it breathe)

Consider:
1. Pacing - {{pacing}} pacing affects shot duration (fast=shorter, slow=longer)
2. Dialogue - shots with speaking characters need lip-sync (needsLipSync: true) and LONGER durations (10-20s)
3. Visual variety - mix shot types AND durations for professional look
4. Story beats - establish (6-10s), develop (5-6s), climax (5s for impact)
5. Scene mood - {{mood}} mood affects rhythm

Available shot types: {{available_shot_types}}

Return ONLY valid JSON (no markdown, no explanation):
{
  "shotCount": number,
  "reasoning": "brief explanation of shot and DURATION choices",
  "shots": [
    {
      "type": "shot_type_slug",
      "duration": number (MUST vary: 5 for close-ups/action, 6 for medium/standard, 10 for establishing/dialogue, 15-20 for long dialogue),
      "purpose": "why this shot",
      "cameraMovement": "movement description",
      "needsLipSync": boolean
    }
  ]
}',
                'default_value' => null,
                'input_type' => 'textarea',
                'input_help' => 'Customize how AI analyzes scenes. Use {{variables}} for dynamic content.',
                'icon' => 'fa-solid fa-message',
                'is_system' => true,
                'sort_order' => 5,
            ],

            // =============================================
            // ANIMATION MODEL SETTINGS
            // =============================================
            [
                'slug' => 'animation_default_model',
                'name' => 'Default Animation Model',
                'category' => 'animation',
                'description' => 'The default video animation model to use for standard shots.',
                'value_type' => 'string',
                'value' => 'minimax',
                'default_value' => 'minimax',
                'allowed_values' => ['minimax', 'multitalk'],
                'input_type' => 'select',
                'input_help' => 'MiniMax for general animation, Multitalk for lip-sync dialogue',
                'icon' => 'fa-solid fa-wand-magic-sparkles',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'animation_minimax_durations',
                'name' => 'MiniMax Duration Options',
                'category' => 'animation',
                'description' => 'Available duration options for MiniMax video generation (in seconds).',
                'value_type' => 'json',
                'value' => '[5, 6, 10]',
                'default_value' => '[5, 6, 10]',
                'input_type' => 'json_editor',
                'input_help' => 'Array of durations in seconds. MiniMax supports 5s, 6s, and 10s.',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'animation_minimax_default_duration',
                'name' => 'MiniMax Default Duration',
                'category' => 'animation',
                'description' => 'Default duration for MiniMax video generation.',
                'value_type' => 'integer',
                'value' => '6',
                'default_value' => '6',
                'allowed_values' => [5, 6, 10],
                'input_type' => 'select',
                'input_help' => 'Standard duration when not specified by AI or user',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'animation_multitalk_durations',
                'name' => 'Multitalk Duration Options',
                'category' => 'animation',
                'description' => 'Available duration options for Multitalk lip-sync video generation (in seconds).',
                'value_type' => 'json',
                'value' => '[5, 10, 15, 20]',
                'default_value' => '[5, 10, 15, 20]',
                'input_type' => 'json_editor',
                'input_help' => 'Array of durations in seconds. Multitalk supports longer durations for dialogue.',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'animation_multitalk_default_duration',
                'name' => 'Multitalk Default Duration',
                'category' => 'animation',
                'description' => 'Default duration for Multitalk lip-sync video generation.',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'allowed_values' => [5, 10, 15, 20],
                'input_type' => 'select',
                'input_help' => 'Standard duration for dialogue scenes',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'animation_auto_select_model',
                'name' => 'Auto-Select Model by Content',
                'category' => 'animation',
                'description' => 'Automatically select Multitalk for dialogue shots and MiniMax for others.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, shots with dialogue automatically use Multitalk if available',
                'icon' => 'fa-solid fa-robot',
                'is_system' => true,
                'sort_order' => 6,
            ],

            // =============================================
            // DURATION SETTINGS
            // =============================================
            [
                'slug' => 'duration_shot_min',
                'name' => 'Minimum Shot Duration',
                'category' => 'duration',
                'description' => 'Minimum duration for any individual shot (in seconds).',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Very short shots (under 3s) may feel too rushed',
                'icon' => 'fa-solid fa-hourglass-start',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'duration_shot_max',
                'name' => 'Maximum Shot Duration',
                'category' => 'duration',
                'description' => 'Maximum duration for any individual shot (in seconds).',
                'value_type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'min_value' => 5,
                'max_value' => 60,
                'input_type' => 'number',
                'input_help' => 'Long shots are supported by Multitalk for extended dialogue',
                'icon' => 'fa-solid fa-hourglass-end',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'duration_shot_default',
                'name' => 'Default Shot Duration',
                'category' => 'duration',
                'description' => 'Default duration when not specified by AI or user.',
                'value_type' => 'integer',
                'value' => '6',
                'default_value' => '6',
                'min_value' => 3,
                'max_value' => 20,
                'input_type' => 'number',
                'input_help' => '6 seconds is optimal for most shot types',
                'icon' => 'fa-solid fa-stopwatch',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'duration_per_shot_enabled',
                'name' => 'Enable Per-Shot Duration',
                'category' => 'duration',
                'description' => 'Allow different durations for each shot within a scene (vs. uniform duration).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, each shot can have its own duration based on content',
                'icon' => 'fa-solid fa-sliders',
                'is_system' => true,
                'sort_order' => 4,
            ],

            // =============================================
            // SCENE PROCESSING SETTINGS
            // =============================================
            [
                'slug' => 'scene_duration_min',
                'name' => 'Minimum Scene Duration',
                'category' => 'scene',
                'description' => 'Minimum duration for any scene (in seconds).',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'min_value' => 5,
                'max_value' => 30,
                'input_type' => 'number',
                'input_help' => 'Scenes shorter than this may not have enough content',
                'icon' => 'fa-solid fa-minimize',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'scene_duration_max',
                'name' => 'Maximum Scene Duration',
                'category' => 'scene',
                'description' => 'Maximum duration for any scene (in seconds).',
                'value_type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'min_value' => 15,
                'max_value' => 300,
                'input_type' => 'number',
                'input_help' => 'Very long scenes should be split into multiple scenes',
                'icon' => 'fa-solid fa-maximize',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'scene_duration_default',
                'name' => 'Default Scene Duration',
                'category' => 'scene',
                'description' => 'Default duration when generating new scenes.',
                'value_type' => 'integer',
                'value' => '15',
                'default_value' => '15',
                'min_value' => 10,
                'max_value' => 60,
                'input_type' => 'number',
                'input_help' => '15 seconds provides good balance of content and pacing',
                'icon' => 'fa-solid fa-clock',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'scene_auto_decompose',
                'name' => 'Auto-Decompose Scenes',
                'category' => 'scene',
                'description' => 'Automatically decompose scenes into shots when entering animation phase.',
                'value_type' => 'boolean',
                'value' => 'false',
                'default_value' => 'false',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, all scenes are automatically decomposed without manual trigger',
                'icon' => 'fa-solid fa-wand-magic',
                'is_system' => true,
                'sort_order' => 4,
            ],

            // =============================================
            // GENERAL WIZARD SETTINGS
            // =============================================
            [
                'slug' => 'frame_chaining_enabled',
                'name' => 'Enable Frame Chaining',
                'category' => 'general',
                'description' => 'Use last frame of previous shot as starting frame for next shot (ensures visual continuity).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Recommended for professional-looking shot transitions',
                'icon' => 'fa-solid fa-link',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'style_bible_enforcement',
                'name' => 'Style Bible Enforcement Level',
                'category' => 'general',
                'description' => 'How strictly to apply Style Bible settings to generated content.',
                'value_type' => 'string',
                'value' => 'moderate',
                'default_value' => 'moderate',
                'allowed_values' => ['strict', 'moderate', 'loose'],
                'input_type' => 'select',
                'input_help' => 'Strict: exact match required, Moderate: balanced, Loose: general guidance',
                'icon' => 'fa-solid fa-palette',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'parallel_generation_limit',
                'name' => 'Parallel Generation Limit',
                'category' => 'general',
                'description' => 'Maximum number of shots/images to generate in parallel.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 1,
                'max_value' => 10,
                'input_type' => 'number',
                'input_help' => 'Higher values speed up generation but may hit API rate limits',
                'icon' => 'fa-solid fa-layer-group',
                'is_system' => true,
                'sort_order' => 3,
            ],

            // =============================================
            // API ENDPOINTS SETTINGS
            // =============================================
            [
                'slug' => 'api_runpod_key',
                'name' => 'RunPod API Key',
                'category' => 'api',
                'description' => 'API key for RunPod serverless endpoints (Multitalk, HiDream, etc.).',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'password',
                'input_help' => 'Get your API key from runpod.io dashboard',
                'icon' => 'fa-solid fa-key',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'api_runpod_multitalk_endpoint',
                'name' => 'RunPod Multitalk Endpoint',
                'category' => 'api',
                'description' => 'RunPod serverless endpoint URL for Multitalk lip-sync video generation.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Format: https://api.runpod.ai/v2/{endpoint_id}/run',
                'icon' => 'fa-solid fa-video',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'api_runpod_hidream_endpoint',
                'name' => 'RunPod HiDream Endpoint',
                'category' => 'api',
                'description' => 'RunPod serverless endpoint URL for HiDream image generation.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Format: https://api.runpod.ai/v2/{endpoint_id}/run',
                'icon' => 'fa-solid fa-image',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'api_minimax_key',
                'name' => 'MiniMax API Key',
                'category' => 'api',
                'description' => 'API key for MiniMax video generation service.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'password',
                'input_help' => 'Required for image-to-video animation',
                'icon' => 'fa-solid fa-key',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'api_minimax_group_id',
                'name' => 'MiniMax Group ID',
                'category' => 'api',
                'description' => 'Group ID for MiniMax API authentication.',
                'value_type' => 'string',
                'value' => '',
                'default_value' => '',
                'input_type' => 'text',
                'input_help' => 'Found in your MiniMax dashboard',
                'icon' => 'fa-solid fa-users',
                'is_system' => true,
                'sort_order' => 5,
            ],

            // =============================================
            // CREDIT COSTS SETTINGS
            // =============================================
            [
                'slug' => 'credits_script_generation',
                'name' => 'Script Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating a new script.',
                'value_type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost per script generation request',
                'icon' => 'fa-solid fa-scroll',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'credits_image_generation',
                'name' => 'Image Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating a single image.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per image generation',
                'icon' => 'fa-solid fa-image',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'credits_voiceover_generation',
                'name' => 'Voiceover Generation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for generating voiceover audio.',
                'value_type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per voiceover generation',
                'icon' => 'fa-solid fa-microphone',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'credits_video_animation',
                'name' => 'Video Animation Cost',
                'category' => 'credits',
                'description' => 'Credits charged for animating a single shot/image.',
                'value_type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost per video animation (MiniMax or Multitalk)',
                'icon' => 'fa-solid fa-video',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'credits_video_export',
                'name' => 'Video Export Cost',
                'category' => 'credits',
                'description' => 'Credits charged for exporting final video.',
                'value_type' => 'integer',
                'value' => '15',
                'default_value' => '15',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Cost for final video rendering and export',
                'icon' => 'fa-solid fa-file-export',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'credits_concept_improvement',
                'name' => 'Concept Improvement Cost',
                'category' => 'credits',
                'description' => 'Credits charged for AI concept improvement.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 0,
                'max_value' => 50,
                'input_type' => 'number',
                'input_help' => 'Cost per concept improvement request',
                'icon' => 'fa-solid fa-lightbulb',
                'is_system' => true,
                'sort_order' => 6,
            ],

            // =============================================
            // AI PROVIDER SETTINGS
            // =============================================
            [
                'slug' => 'ai_script_provider',
                'name' => 'Script Generation Provider',
                'category' => 'ai_providers',
                'description' => 'AI provider to use for script generation.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'grok', 'gemini', 'anthropic'],
                'input_type' => 'select',
                'input_help' => 'Select which AI provider generates scripts',
                'icon' => 'fa-solid fa-brain',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'ai_script_model',
                'name' => 'Script Generation Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for script generation.',
                'value_type' => 'string',
                'value' => 'gpt-4',
                'default_value' => 'gpt-4',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., gpt-4, gpt-4-turbo, claude-3-opus)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'ai_shot_analysis_provider',
                'name' => 'Shot Analysis Provider',
                'category' => 'ai_providers',
                'description' => 'AI provider to use for shot intelligence analysis.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'grok', 'gemini', 'anthropic'],
                'input_type' => 'select',
                'input_help' => 'Provider for AI shot decomposition analysis',
                'icon' => 'fa-solid fa-magnifying-glass-chart',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'ai_shot_analysis_model',
                'name' => 'Shot Analysis Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for shot intelligence analysis.',
                'value_type' => 'string',
                'value' => 'gpt-4',
                'default_value' => 'gpt-4',
                'input_type' => 'text',
                'input_help' => 'Recommend GPT-4 or Claude for complex scene analysis',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'ai_image_provider',
                'name' => 'Image Generation Provider',
                'category' => 'ai_providers',
                'description' => 'Default image generation provider.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'hidream', 'stability', 'midjourney'],
                'input_type' => 'select',
                'input_help' => 'OpenAI DALL-E, HiDream, Stability AI, etc.',
                'icon' => 'fa-solid fa-paintbrush',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'ai_image_model',
                'name' => 'Image Generation Model',
                'category' => 'ai_providers',
                'description' => 'AI model to use for image generation.',
                'value_type' => 'string',
                'value' => 'dall-e-3',
                'default_value' => 'dall-e-3',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., dall-e-3, hidream-i1-full)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'ai_voiceover_provider',
                'name' => 'Voiceover Provider',
                'category' => 'ai_providers',
                'description' => 'TTS provider for voiceover generation.',
                'value_type' => 'string',
                'value' => 'openai',
                'default_value' => 'openai',
                'allowed_values' => ['openai', 'elevenlabs', 'google'],
                'input_type' => 'select',
                'input_help' => 'Text-to-speech provider',
                'icon' => 'fa-solid fa-volume-high',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'ai_voiceover_model',
                'name' => 'Voiceover Model',
                'category' => 'ai_providers',
                'description' => 'TTS model for voiceover generation.',
                'value_type' => 'string',
                'value' => 'tts-1-hd',
                'default_value' => 'tts-1-hd',
                'input_type' => 'text',
                'input_help' => 'Model name (e.g., tts-1-hd, eleven_multilingual_v2)',
                'icon' => 'fa-solid fa-microchip',
                'is_system' => true,
                'sort_order' => 8,
            ],

            // =============================================
            // PRODUCTION INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'production_auto_multishot_types',
                'name' => 'Auto-Enable Multi-Shot for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Multi-Shot Mode. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial,music-video',
                'default_value' => 'movie,documentary,commercial,music-video',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary,commercial - these types auto-enable multi-shot decomposition',
                'icon' => 'fa-solid fa-film',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'production_auto_character_bible_types',
                'name' => 'Auto-Enable Character Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Character Bible detection. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial,narrative',
                'default_value' => 'movie,documentary,commercial,narrative',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary - these types auto-detect and track characters',
                'icon' => 'fa-solid fa-users',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'production_main_char_scene_percent',
                'name' => 'Main Character Scene Percentage',
                'category' => 'production_intelligence',
                'description' => 'Minimum percentage of scenes where Main characters should appear (cinematic continuity).',
                'value_type' => 'integer',
                'value' => '70',
                'default_value' => '70',
                'min_value' => 30,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Main characters will be expanded to appear in at least this % of scenes',
                'icon' => 'fa-solid fa-star',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'production_supporting_char_scene_percent',
                'name' => 'Supporting Character Scene Percentage',
                'category' => 'production_intelligence',
                'description' => 'Minimum percentage of scenes where Supporting characters should appear.',
                'value_type' => 'integer',
                'value' => '40',
                'default_value' => '40',
                'min_value' => 10,
                'max_value' => 80,
                'input_type' => 'number',
                'input_help' => 'Supporting characters will be expanded to appear in at least this % of scenes',
                'icon' => 'fa-solid fa-user-group',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'production_portrait_single_person',
                'name' => 'Enforce Single-Person Portraits',
                'category' => 'production_intelligence',
                'description' => 'When enabled, character portrait generation strictly enforces single-person output.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Adds strong single-person directives to portrait prompts',
                'icon' => 'fa-solid fa-portrait',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'production_auto_location_bible_types',
                'name' => 'Auto-Enable Location Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Location Bible detection. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,commercial',
                'default_value' => 'movie,documentary,commercial',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,documentary - these types auto-detect and track locations',
                'icon' => 'fa-solid fa-location-dot',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'production_auto_style_bible_types',
                'name' => 'Auto-Enable Style Bible for Production Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that automatically enable Style Bible. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,commercial,music-video',
                'default_value' => 'movie,commercial,music-video',
                'input_type' => 'text',
                'input_help' => 'E.g., movie,commercial - these types auto-enable visual style consistency',
                'icon' => 'fa-solid fa-palette',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'production_narrative_tracking_types',
                'name' => 'Narrative Continuity Tracking Types',
                'category' => 'production_intelligence',
                'description' => 'Production types that use narrative (not literal) character tracking. Comma-separated list.',
                'value_type' => 'string',
                'value' => 'movie,documentary,narrative',
                'default_value' => 'movie,documentary,narrative',
                'input_type' => 'text',
                'input_help' => 'Narrative tracking expands character presence based on story logic, not just mentions',
                'icon' => 'fa-solid fa-book-open',
                'is_system' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'production_type_overrides',
                'name' => 'Per-Production-Type Overrides',
                'category' => 'production_intelligence',
                'description' => 'JSON object with custom settings per production type. Overrides global defaults.',
                'value_type' => 'json',
                'value' => '{}',
                'default_value' => '{}',
                'input_type' => 'textarea',
                'input_help' => 'Example: {"movie":{"mainCharScenePercent":80},"commercial":{"mainCharScenePercent":60}}',
                'icon' => 'fa-solid fa-sliders',
                'is_system' => true,
                'sort_order' => 9,
            ],

            // =============================================
            // CINEMATIC INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'cinematic_intelligence_enabled',
                'name' => 'Enable Cinematic Intelligence',
                'category' => 'cinematic_intelligence',
                'description' => 'Master toggle for all Hollywood-level cinematic intelligence features.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Enables character state tracking, emotional arcs, wardrobe continuity, and more',
                'icon' => 'fa-solid fa-clapperboard',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'character_state_tracking_enabled',
                'name' => 'Character State Tracking',
                'category' => 'cinematic_intelligence',
                'description' => 'Track character states (mood, wardrobe, injuries, props) across all scenes.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Ensures continuity by propagating state changes through scenes',
                'icon' => 'fa-solid fa-user-check',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'emotional_arc_enabled',
                'name' => 'Emotional Arc Engine',
                'category' => 'cinematic_intelligence',
                'description' => 'Auto-generate emotional arcs for characters based on role and genre.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Creates a hero journey emotional progression across scenes',
                'icon' => 'fa-solid fa-heart-pulse',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'wardrobe_continuity_enabled',
                'name' => 'Wardrobe Continuity Validation',
                'category' => 'cinematic_intelligence',
                'description' => 'Validate wardrobe consistency across consecutive scenes.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Flags unexpected wardrobe changes between scenes',
                'icon' => 'fa-solid fa-shirt',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'location_character_binding_enabled',
                'name' => 'Location-Character Auto-Binding',
                'category' => 'cinematic_intelligence',
                'description' => 'Infer character presence based on location continuity between scenes.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'If character was at location X in scene N, suggests presence in scene N+1 at same location',
                'icon' => 'fa-solid fa-location-crosshairs',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'shot_type_rules_enabled',
                'name' => 'Shot-Type Character Rules',
                'category' => 'cinematic_intelligence',
                'description' => 'Enforce shot-type specific character limits (e.g., close-up = 1 person only).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Validates character counts per shot type for professional framing',
                'icon' => 'fa-solid fa-camera',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'scene_transition_intelligence_enabled',
                'name' => 'Scene Transition Intelligence',
                'category' => 'cinematic_intelligence',
                'description' => 'Auto-classify scene types and suggest optimal shot sequences.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Identifies dialogue, action, emotional, flashback scenes and recommends shots',
                'icon' => 'fa-solid fa-right-left',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'reference_image_chain_enabled',
                'name' => 'Reference Image Chain',
                'category' => 'cinematic_intelligence',
                'description' => 'Build reference image chains for character consistency across scenes.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Uses first appearance images as reference for subsequent scenes',
                'icon' => 'fa-solid fa-link',
                'is_system' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'character_relationship_mapping_enabled',
                'name' => 'Character Relationship Mapping',
                'category' => 'cinematic_intelligence',
                'description' => 'Map relationships between characters for framing suggestions.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Allies, enemies, romantic, family - affects proximity and body language',
                'icon' => 'fa-solid fa-people-arrows',
                'is_system' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'narrative_beat_alignment_enabled',
                'name' => 'Narrative Beat Alignment',
                'category' => 'cinematic_intelligence',
                'description' => 'Assign story beats to scenes (setup, inciting incident, climax, etc.).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Ensures proper story structure and main character presence at key beats',
                'icon' => 'fa-solid fa-book-open',
                'is_system' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'consistency_scoring_enabled',
                'name' => 'Consistency Scoring System',
                'category' => 'cinematic_intelligence',
                'description' => 'Calculate comprehensive consistency scores for projects.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Provides letter grades (A+ to F) based on character presence, wardrobe, emotional arc, etc.',
                'icon' => 'fa-solid fa-chart-line',
                'is_system' => true,
                'sort_order' => 11,
            ],
            [
                'slug' => 'consistency_score_threshold',
                'name' => 'Minimum Consistency Score',
                'category' => 'cinematic_intelligence',
                'description' => 'Minimum consistency score threshold for warnings (0.0-1.0).',
                'value_type' => 'float',
                'value' => '0.70',
                'default_value' => '0.70',
                'min_value' => 0,
                'max_value' => 1,
                'input_type' => 'number',
                'input_help' => 'Projects below this score will show warnings (0.70 = B- grade)',
                'icon' => 'fa-solid fa-gauge',
                'is_system' => true,
                'sort_order' => 12,
            ],
            [
                'slug' => 'default_genre',
                'name' => 'Default Genre for Emotional Arcs',
                'category' => 'cinematic_intelligence',
                'description' => 'Default genre used for generating emotional arcs when not specified.',
                'value_type' => 'string',
                'value' => 'drama',
                'default_value' => 'drama',
                'allowed_values' => ['drama', 'comedy', 'thriller', 'action', 'horror'],
                'input_type' => 'select',
                'input_help' => 'Different genres have different emotional arc patterns',
                'icon' => 'fa-solid fa-masks-theater',
                'is_system' => true,
                'sort_order' => 13,
            ],

            // =============================================
            // MOTION INTELLIGENCE SETTINGS
            // =============================================
            [
                'slug' => 'motion_intelligence_enabled',
                'name' => 'Enable Motion Intelligence',
                'category' => 'motion_intelligence',
                'description' => 'When enabled, AI will select optimal camera movements based on shot type, emotion, and scene context.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Automatically suggests camera movements for each shot based on cinematography best practices',
                'icon' => 'fa-solid fa-video',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'movement_stacking_enabled',
                'name' => 'Enable Movement Stacking',
                'category' => 'motion_intelligence',
                'description' => 'Allow combining multiple camera movements (e.g., dolly in + crane up) for complex cinematic motion.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Based on Higgsfield methodology - stack up to 2-3 movements for professional results',
                'icon' => 'fa-solid fa-layer-group',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'max_stacked_movements',
                'name' => 'Max Stacked Movements',
                'category' => 'motion_intelligence',
                'description' => 'Maximum number of camera movements that can be combined in a single shot.',
                'value_type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'min_value' => 1,
                'max_value' => 3,
                'input_type' => 'number',
                'input_help' => 'Recommended: 2 for balanced results, 3 for complex professional motion',
                'icon' => 'fa-solid fa-hashtag',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'default_movement_intensity',
                'name' => 'Default Movement Intensity',
                'category' => 'motion_intelligence',
                'description' => 'Default intensity level for camera movements when not specified by context.',
                'value_type' => 'string',
                'value' => 'moderate',
                'default_value' => 'moderate',
                'allowed_values' => ['subtle', 'moderate', 'dynamic', 'intense'],
                'input_type' => 'select',
                'input_help' => 'Subtle: slow/gentle, Moderate: smooth/balanced, Dynamic: energetic, Intense: dramatic',
                'icon' => 'fa-solid fa-gauge',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'auto_select_movement',
                'name' => 'Auto-Select Movement by Shot Type',
                'category' => 'motion_intelligence',
                'description' => 'Automatically select camera movement based on shot type and emotional context.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, AI picks the best movement for each shot type automatically',
                'icon' => 'fa-solid fa-wand-magic-sparkles',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'default_camera_movement',
                'name' => 'Default Camera Movement',
                'category' => 'motion_intelligence',
                'description' => 'Default camera movement when no specific movement is recommended.',
                'value_type' => 'string',
                'value' => 'static',
                'default_value' => 'static',
                'input_type' => 'text',
                'input_help' => 'Movement slug to use as fallback (e.g., static, push-in, dolly-in)',
                'icon' => 'fa-solid fa-camera',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'video_prompt_quality_level',
                'name' => 'Video Prompt Quality Level',
                'category' => 'motion_intelligence',
                'description' => 'Default quality level for video animation prompts.',
                'value_type' => 'string',
                'value' => 'cinematic',
                'default_value' => 'cinematic',
                'allowed_values' => ['broadcast', 'cinematic', 'premium', 'social'],
                'input_type' => 'select',
                'input_help' => 'Higher quality = more detailed prompts, premium adds 8K/IMAX markers',
                'icon' => 'fa-solid fa-star',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'video_prompt_include_lighting',
                'name' => 'Include Lighting in Video Prompts',
                'category' => 'motion_intelligence',
                'description' => 'Automatically add lighting descriptions to video animation prompts.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Adds context-aware lighting descriptions for visual consistency',
                'icon' => 'fa-solid fa-lightbulb',
                'is_system' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'video_prompt_include_atmosphere',
                'name' => 'Include Atmosphere in Video Prompts',
                'category' => 'motion_intelligence',
                'description' => 'Add atmospheric/environmental descriptions to video prompts.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Includes weather, particles, and mood-based atmosphere',
                'icon' => 'fa-solid fa-cloud',
                'is_system' => true,
                'sort_order' => 9,
            ],

            // =============================================
            // SHOT CONTINUITY SETTINGS (Phase 3)
            // =============================================
            [
                'slug' => 'shot_continuity_enabled',
                'name' => 'Enable Shot Continuity System',
                'category' => 'shot_continuity',
                'description' => 'Master toggle for shot continuity analysis and suggestions. Ensures professional shot sequencing.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Analyzes shot sequences for compatibility, 30-degree rule, and movement continuity',
                'icon' => 'fa-solid fa-link',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'shot_continuity_min_score',
                'name' => 'Minimum Continuity Score',
                'category' => 'shot_continuity',
                'description' => 'Minimum compatibility score (0-100) before showing warnings about awkward transitions.',
                'value_type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Transitions scoring below this threshold will be flagged for review',
                'icon' => 'fa-solid fa-gauge',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'shot_continuity_30_degree_rule',
                'name' => 'Enforce 30-Degree Rule',
                'category' => 'shot_continuity',
                'description' => 'Warn when consecutive shots of same size don\'t have significant angle change.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Classic filmmaking rule: camera should move at least 30 degrees between similar shots',
                'icon' => 'fa-solid fa-rotate',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'shot_continuity_auto_optimize',
                'name' => 'Auto-Optimize Shot Sequences',
                'category' => 'shot_continuity',
                'description' => 'Automatically insert transition shots when incompatible shots are detected.',
                'value_type' => 'boolean',
                'value' => 'false',
                'default_value' => 'false',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, the system will suggest and can auto-insert cutaways or reaction shots',
                'icon' => 'fa-solid fa-wand-magic-sparkles',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'shot_continuity_coverage_patterns',
                'name' => 'Enable Coverage Pattern Suggestions',
                'category' => 'shot_continuity',
                'description' => 'Suggest professional coverage patterns based on scene type (dialogue, action, etc.).',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Dialogue scenes: Master → OTS A → OTS B → CU A → CU B pattern',
                'icon' => 'fa-solid fa-list-check',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'shot_continuity_movement_flow',
                'name' => 'Check Movement Flow',
                'category' => 'shot_continuity',
                'description' => 'Analyze camera movement continuity between consecutive shots.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Warns about jarring transitions like intense movement → static (without transition)',
                'icon' => 'fa-solid fa-wind',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'shot_continuity_jump_cut_detection',
                'name' => 'Detect Jump Cuts',
                'category' => 'shot_continuity',
                'description' => 'Flag potential jump cuts (same subject, minor position change) as issues.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Jump cuts are jarring edits that break continuity (unless used stylistically)',
                'icon' => 'fa-solid fa-scissors',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'shot_continuity_default_scene_type',
                'name' => 'Default Scene Type',
                'category' => 'shot_continuity',
                'description' => 'Default scene type for coverage pattern suggestions when not detected.',
                'value_type' => 'string',
                'value' => 'dialogue',
                'default_value' => 'dialogue',
                'allowed_values' => ['dialogue', 'action', 'montage', 'emotional', 'establishing'],
                'input_type' => 'select',
                'input_help' => 'Different scene types have different optimal shot patterns',
                'icon' => 'fa-solid fa-film',
                'is_system' => true,
                'sort_order' => 8,
            ],

            // =============================================
            // SCENE DETECTION SETTINGS (Phase 4)
            // =============================================
            [
                'slug' => 'scene_detection_enabled',
                'name' => 'Enable Scene Type Detection',
                'category' => 'scene_detection',
                'description' => 'Master toggle for automatic scene type detection and coverage pattern suggestions.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Automatically classifies scenes as dialogue, action, emotional, etc.',
                'icon' => 'fa-solid fa-magnifying-glass-chart',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'scene_detection_auto',
                'name' => 'Auto-Detect on Scene Analysis',
                'category' => 'scene_detection',
                'description' => 'Automatically detect scene type when analyzing scenes for shot breakdown.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'When enabled, scene type is detected automatically during shot intelligence analysis',
                'icon' => 'fa-solid fa-robot',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'scene_detection_min_confidence',
                'name' => 'Minimum Detection Confidence',
                'category' => 'scene_detection',
                'description' => 'Minimum confidence score (0-100) required to accept a scene type detection.',
                'value_type' => 'integer',
                'value' => '40',
                'default_value' => '40',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Lower values detect more scenes but with less accuracy; higher values are more selective',
                'icon' => 'fa-solid fa-gauge',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'scene_detection_default_type',
                'name' => 'Default Scene Type',
                'category' => 'scene_detection',
                'description' => 'Default scene type when detection fails or confidence is too low.',
                'value_type' => 'string',
                'value' => 'dialogue',
                'default_value' => 'dialogue',
                'allowed_values' => ['dialogue', 'action', 'emotional', 'montage', 'establishing'],
                'input_type' => 'select',
                'input_help' => 'Fallback scene type (dialogue is most common in most productions)',
                'icon' => 'fa-solid fa-list',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'scene_detection_use_context',
                'name' => 'Use Contextual Detection',
                'category' => 'scene_detection',
                'description' => 'Consider genre, previous scenes, and story position when detecting scene type.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Improves accuracy by considering surrounding context',
                'icon' => 'fa-solid fa-diagram-project',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'scene_detection_track_accuracy',
                'name' => 'Track Detection Accuracy',
                'category' => 'scene_detection',
                'description' => 'Track and learn from user corrections to improve detection over time.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Patterns with better success rates will be prioritized',
                'icon' => 'fa-solid fa-chart-line',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'scene_detection_suggest_alternatives',
                'name' => 'Suggest Alternative Patterns',
                'category' => 'scene_detection',
                'description' => 'Show alternative coverage pattern suggestions alongside the primary detection.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Shows up to 3 alternative patterns the user can choose from',
                'icon' => 'fa-solid fa-list-check',
                'is_system' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'scene_detection_max_alternatives',
                'name' => 'Max Alternative Suggestions',
                'category' => 'scene_detection',
                'description' => 'Maximum number of alternative patterns to suggest.',
                'value_type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'min_value' => 0,
                'max_value' => 5,
                'input_type' => 'number',
                'input_help' => 'Number of backup options shown to users',
                'icon' => 'fa-solid fa-hashtag',
                'is_system' => true,
                'sort_order' => 8,
            ],

            // =============================================
            // SHOT PROGRESSION SETTINGS (Phase 6)
            // =============================================
            [
                'slug' => 'shot_progression_enabled',
                'name' => 'Enable Shot Progression System',
                'category' => 'shot_progression',
                'description' => 'Master toggle for shot progression analysis. Ensures each shot advances the narrative with unique story beats and actions.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Uses Tension Curve and Emotional Journey selections to create energy and mood progression',
                'icon' => 'fa-solid fa-diagram-project',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'shot_progression_action_continuity',
                'name' => 'Validate Action Continuity',
                'category' => 'shot_progression',
                'description' => 'Detect and flag consecutive shots with identical or too-similar actions to prevent static sequences.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Flags shots like "man smiles" → "man smiles" as needing action progression',
                'icon' => 'fa-solid fa-person-walking',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'shot_progression_flag_static',
                'name' => 'Flag Static Shot Sequences',
                'category' => 'shot_progression',
                'description' => 'Show warnings when multiple consecutive shots have the same action description.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Helps editors identify and fix repetitive shot sequences',
                'icon' => 'fa-solid fa-triangle-exclamation',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'shot_progression_enhance_prompts',
                'name' => 'Enhance Prompts with Progression',
                'category' => 'shot_progression',
                'description' => 'Automatically add story beat, energy level, and mood context to video prompts.',
                'value_type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'input_type' => 'checkbox',
                'input_help' => 'Adds context like "[Discovery beat, rising energy, hopeful mood]" to prompts',
                'icon' => 'fa-solid fa-wand-magic-sparkles',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'shot_progression_min_score',
                'name' => 'Minimum Progression Score',
                'category' => 'shot_progression',
                'description' => 'Minimum progression quality score (0-100) before showing warnings about weak narrative flow.',
                'value_type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'min_value' => 0,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Shots scoring below this threshold will be flagged for narrative improvement',
                'icon' => 'fa-solid fa-gauge',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'shot_progression_similarity_threshold',
                'name' => 'Action Similarity Threshold',
                'category' => 'shot_progression',
                'description' => 'Maximum text similarity (0-100) allowed between consecutive shot actions before flagging as duplicate.',
                'value_type' => 'integer',
                'value' => '85',
                'default_value' => '85',
                'min_value' => 50,
                'max_value' => 100,
                'input_type' => 'number',
                'input_help' => 'Actions with similarity above this % are flagged (85% catches near-identical actions)',
                'icon' => 'fa-solid fa-equals',
                'is_system' => true,
                'sort_order' => 6,
            ],
        ];

        foreach ($settings as $setting) {
            VwSetting::updateOrCreate(
                ['slug' => $setting['slug']],
                $setting
            );
        }

        // Clear cache after seeding
        VwSetting::clearCache();
    }
}
