<?php

namespace Modules\AppVideoWizard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AppVideoWizard\Models\VwShotType;

class VwShotTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 50+ professional shot types based on StudioBinder's Camera Shots Guide.
     */
    public function run(): void
    {
        $shotTypes = [
            // ===== FRAMING SHOTS (Shot Size) =====
            [
                'slug' => 'extreme-wide',
                'name' => 'Extreme Wide Shot (EWS)',
                'category' => 'framing',
                'description' => 'Shows entire location with subject appearing tiny. Used for establishing scale and isolation.',
                'camera_specs' => 'Ultra-wide 14-16mm lens, deep focus, f/8-11',
                'default_lens' => '14mm',
                'default_aperture' => 'f/8',
                'typical_duration_min' => 4,
                'typical_duration_max' => 10,
                'emotional_beats' => json_encode(['establishing', 'isolation', 'scale', 'wonder']),
                'best_for_genres' => json_encode(['epic', 'documentary', 'thriller']),
                'prompt_template' => 'Extreme wide shot of {subject}, vast {environment}, subject tiny in frame, {lens_spec}',
                'motion_description' => 'Slow pan revealing the vast scale of the environment',
                'compatible_transitions' => json_encode(['wide', 'medium-wide', 'aerial']),
                'sort_order' => 1,
            ],
            [
                'slug' => 'very-wide',
                'name' => 'Very Wide Shot (VWS)',
                'category' => 'framing',
                'description' => 'Subject visible but environment dominates the frame.',
                'camera_specs' => 'Wide 18-24mm lens, f/5.6-8',
                'default_lens' => '21mm',
                'default_aperture' => 'f/5.6',
                'typical_duration_min' => 4,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['context', 'journey', 'environment']),
                'best_for_genres' => json_encode(['adventure', 'drama', 'documentary']),
                'prompt_template' => 'Very wide shot showing {subject} within {environment}, environmental context prominent',
                'motion_description' => 'Slow drift establishing the relationship between subject and environment',
                'compatible_transitions' => json_encode(['wide', 'medium-wide', 'establishing']),
                'sort_order' => 2,
            ],
            [
                'slug' => 'wide',
                'name' => 'Wide Shot (WS)',
                'category' => 'framing',
                'description' => 'Full body visible with surrounding environment. Classic establishing shot.',
                'camera_specs' => 'Wide 24-35mm lens, f/4-5.6',
                'default_lens' => '24mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['establishing', 'geography', 'movement', 'introduction']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Wide shot of {subject}, full body visible, {environment} context, {camera_movement}',
                'motion_description' => 'Subtle movement establishing scene geography',
                'compatible_transitions' => json_encode(['medium-wide', 'medium', 'full', 'over-shoulder']),
                'sort_order' => 3,
            ],
            [
                'slug' => 'full',
                'name' => 'Full Shot (FS)',
                'category' => 'framing',
                'description' => 'Head to toe framing of subject. Good for action and movement.',
                'camera_specs' => 'Standard 35-50mm lens, f/2.8-4',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 7,
                'emotional_beats' => json_encode(['introduction', 'action', 'dance', 'movement']),
                'best_for_genres' => json_encode(['action', 'comedy', 'drama']),
                'prompt_template' => 'Full shot of {subject}, head to toe visible, {camera_movement}',
                'motion_description' => 'Following subject movement while maintaining full body framing',
                'compatible_transitions' => json_encode(['medium-wide', 'medium', 'wide']),
                'sort_order' => 4,
            ],
            [
                'slug' => 'medium-wide',
                'name' => 'Medium Wide Shot (MWS)',
                'category' => 'framing',
                'description' => 'Knees up framing, also called 3/4 shot. Balances subject and environment.',
                'camera_specs' => 'Standard 35-50mm lens, f/2.8',
                'default_lens' => '40mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['dialogue', 'group', 'movement', 'interaction']),
                'best_for_genres' => json_encode(['drama', 'comedy', 'documentary']),
                'prompt_template' => 'Medium wide shot of {subject}, knees up framing, {environment} visible',
                'motion_description' => 'Subtle movement maintaining subject prominence with environmental context',
                'compatible_transitions' => json_encode(['medium', 'full', 'wide', 'two-shot']),
                'sort_order' => 5,
            ],
            [
                'slug' => 'cowboy',
                'name' => 'Cowboy Shot',
                'category' => 'framing',
                'description' => 'Mid-thigh up, originated in Westerns to show holstered guns. Creates tension.',
                'camera_specs' => 'Standard 50mm lens, f/2.8',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['confrontation', 'standoff', 'tension', 'power']),
                'best_for_genres' => json_encode(['western', 'action', 'thriller']),
                'prompt_template' => 'Cowboy shot of {subject}, mid-thigh up, confrontational framing',
                'motion_description' => 'Static or slow push creating tension',
                'compatible_transitions' => json_encode(['medium', 'close-up', 'reaction']),
                'sort_order' => 6,
            ],
            [
                'slug' => 'medium',
                'name' => 'Medium Shot (MS)',
                'category' => 'framing',
                'description' => 'Waist up framing. The workhorse of cinematography for dialogue.',
                'camera_specs' => 'Standard 50mm lens, f/2-2.8',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['dialogue', 'interview', 'reaction', 'narrative']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Medium shot of {subject}, waist up, {camera_movement}, conversational framing',
                'motion_description' => 'Subtle movement maintaining focus on subject expression and gesture',
                'compatible_transitions' => json_encode(['medium-close', 'close-up', 'over-shoulder', 'two-shot']),
                'sort_order' => 7,
            ],
            [
                'slug' => 'medium-close',
                'name' => 'Medium Close-Up (MCU)',
                'category' => 'framing',
                'description' => 'Chest up framing. Intimate but not overwhelming.',
                'camera_specs' => 'Portrait 50-85mm lens, f/1.8-2.8',
                'default_lens' => '65mm',
                'default_aperture' => 'f/2',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['emotion', 'dialogue', 'intimacy', 'connection']),
                'best_for_genres' => json_encode(['drama', 'romance', 'documentary']),
                'prompt_template' => 'Medium close-up of {subject}, chest up, intimate framing, {lens_spec}',
                'motion_description' => 'Gentle push in for emotional emphasis',
                'compatible_transitions' => json_encode(['close-up', 'medium', 'over-shoulder']),
                'sort_order' => 8,
            ],
            [
                'slug' => 'close-up',
                'name' => 'Close-Up (CU)',
                'category' => 'framing',
                'description' => 'Face fills frame. Maximum emotional impact.',
                'camera_specs' => 'Portrait 85mm lens, f/1.4-2, shallow depth of field',
                'default_lens' => '85mm',
                'default_aperture' => 'f/1.4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['emotion', 'intensity', 'reaction', 'revelation', 'intimacy']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Close-up of {subject}, face filling frame, {lens_spec}, shallow depth of field, {camera_movement}',
                'motion_description' => 'Slow push in emphasizing emotional intensity',
                'compatible_transitions' => json_encode(['big-close-up', 'medium-close', 'reaction', 'detail']),
                'sort_order' => 9,
            ],
            [
                'slug' => 'big-close-up',
                'name' => 'Big Close-Up (BCU)',
                'category' => 'framing',
                'description' => 'Forehead to chin. Intense emotional moments.',
                'camera_specs' => 'Telephoto 85-135mm lens, f/1.4, very shallow depth of field',
                'default_lens' => '100mm',
                'default_aperture' => 'f/1.4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 4,
                'emotional_beats' => json_encode(['intense-emotion', 'critical-moment', 'revelation', 'breakdown']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'horror']),
                'prompt_template' => 'Big close-up of {subject}, forehead to chin, intense emotional framing, {lens_spec}',
                'motion_description' => 'Near-static with subtle breathing movement',
                'compatible_transitions' => json_encode(['extreme-close-up', 'close-up', 'reaction']),
                'sort_order' => 10,
            ],
            [
                'slug' => 'extreme-close-up',
                'name' => 'Extreme Close-Up (ECU)',
                'category' => 'framing',
                'description' => 'Single feature - eye, mouth, hand. Maximum detail and symbolism.',
                'camera_specs' => 'Macro or 100mm+ telephoto, f/2.8, extreme shallow focus',
                'default_lens' => '100mm macro',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 4,
                'emotional_beats' => json_encode(['detail', 'suspense', 'symbolism', 'tension', 'reveal']),
                'best_for_genres' => json_encode(['thriller', 'horror', 'drama', 'documentary']),
                'prompt_template' => 'Extreme close-up of {subject}, single detail filling frame, macro detail, {camera_movement}',
                'motion_description' => 'Static or imperceptible movement, extreme detail focus',
                'compatible_transitions' => json_encode(['close-up', 'insert', 'cutaway']),
                'sort_order' => 11,
            ],
            [
                'slug' => 'insert',
                'name' => 'Insert Shot',
                'category' => 'framing',
                'description' => 'Close detail of object or action. Provides information or emphasis.',
                'camera_specs' => 'Macro lens or 85mm+, f/2.8-4',
                'default_lens' => '90mm macro',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 1,
                'typical_duration_max' => 3,
                'emotional_beats' => json_encode(['information', 'detail', 'continuity', 'emphasis']),
                'best_for_genres' => json_encode(['thriller', 'drama', 'documentary']),
                'prompt_template' => 'Insert shot of {subject}, detailed close view, informational framing',
                'motion_description' => 'Static or slow reveal of detail',
                'compatible_transitions' => json_encode(['medium', 'close-up', 'reaction']),
                'sort_order' => 12,
            ],
            [
                'slug' => 'cutaway',
                'name' => 'Cutaway',
                'category' => 'framing',
                'description' => 'Shot of related but different subject. Provides context or reaction.',
                'camera_specs' => 'Variable based on subject, typically 35-85mm',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 1,
                'typical_duration_max' => 4,
                'emotional_beats' => json_encode(['transition', 'reaction', 'context', 'pacing']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Cutaway to {subject}, contextual detail, {environment}',
                'motion_description' => 'Quick establishing movement then static',
                'compatible_transitions' => json_encode(['medium', 'wide', 'close-up']),
                'sort_order' => 13,
            ],

            // ===== ANGLE SHOTS =====
            [
                'slug' => 'eye-level',
                'name' => 'Eye Level',
                'category' => 'angle',
                'description' => 'Camera at subject eye level. Neutral, natural perspective.',
                'camera_specs' => 'Any lens, positioned at subject eye height',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['neutral', 'conversation', 'natural', 'equality']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Eye level shot of {subject}, neutral perspective, natural framing',
                'motion_description' => 'Natural movement at eye level',
                'compatible_transitions' => json_encode(['all']),
                'sort_order' => 20,
            ],
            [
                'slug' => 'low-angle',
                'name' => 'Low Angle',
                'category' => 'angle',
                'description' => 'Camera below looking up. Subject appears powerful, dominant.',
                'camera_specs' => 'Wide to normal lens, 24-50mm, low position',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['power', 'dominance', 'heroic', 'intimidation', 'triumph']),
                'best_for_genres' => json_encode(['action', 'thriller', 'superhero', 'epic']),
                'prompt_template' => 'Low angle shot of {subject}, camera looking up, powerful imposing framing',
                'motion_description' => 'Upward tilt or static emphasizing power',
                'compatible_transitions' => json_encode(['high-angle', 'medium', 'wide']),
                'sort_order' => 21,
            ],
            [
                'slug' => 'high-angle',
                'name' => 'High Angle',
                'category' => 'angle',
                'description' => 'Camera above looking down. Subject appears vulnerable, weak.',
                'camera_specs' => 'Normal to wide lens, 35-50mm, elevated position',
                'default_lens' => '40mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['vulnerability', 'weakness', 'overview', 'judgment', 'despair']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'horror']),
                'prompt_template' => 'High angle shot looking down at {subject}, vulnerable diminished framing',
                'motion_description' => 'Looking down, possibly slow descent',
                'compatible_transitions' => json_encode(['low-angle', 'eye-level', 'birds-eye']),
                'sort_order' => 22,
            ],
            [
                'slug' => 'dutch-angle',
                'name' => 'Dutch Angle/Tilt',
                'category' => 'angle',
                'description' => 'Camera tilted on axis. Creates unease, tension, disorientation.',
                'camera_specs' => 'Any lens, camera rotated 15-45 degrees',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['unease', 'tension', 'disorientation', 'madness', 'chaos']),
                'best_for_genres' => json_encode(['horror', 'thriller', 'action', 'experimental']),
                'prompt_template' => 'Dutch angle shot of {subject}, tilted camera creating unease, {camera_movement}',
                'motion_description' => 'Tilted framing with possible rotation',
                'compatible_transitions' => json_encode(['eye-level', 'close-up', 'wide']),
                'sort_order' => 23,
            ],
            [
                'slug' => 'birds-eye',
                'name' => 'Bird\'s Eye View',
                'category' => 'angle',
                'description' => 'Directly overhead shot. God-like perspective, pattern emphasis.',
                'camera_specs' => 'Wide lens, directly overhead, drone or crane',
                'default_lens' => '24mm',
                'default_aperture' => 'f/5.6',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['god-view', 'pattern', 'isolation', 'omniscience', 'scale']),
                'best_for_genres' => json_encode(['thriller', 'drama', 'documentary', 'experimental']),
                'prompt_template' => 'Bird\'s eye view directly above {subject}, overhead perspective, {environment}',
                'motion_description' => 'Static overhead or slow vertical movement',
                'compatible_transitions' => json_encode(['high-angle', 'wide', 'aerial']),
                'sort_order' => 24,
            ],
            [
                'slug' => 'worms-eye',
                'name' => 'Worm\'s Eye View',
                'category' => 'angle',
                'description' => 'Extreme low from ground level. Maximum power emphasis.',
                'camera_specs' => 'Wide lens at ground level, 16-24mm',
                'default_lens' => '16mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['power', 'monumentality', 'awe', 'intimidation']),
                'best_for_genres' => json_encode(['action', 'horror', 'epic']),
                'prompt_template' => 'Worm\'s eye view of {subject}, extreme low angle from ground, monumental framing',
                'motion_description' => 'Ground-level upward perspective',
                'compatible_transitions' => json_encode(['low-angle', 'wide', 'pov']),
                'sort_order' => 25,
            ],
            [
                'slug' => 'over-shoulder',
                'name' => 'Over-the-Shoulder (OTS)',
                'category' => 'angle',
                'description' => 'Behind one subject looking toward another. Classic dialogue shot.',
                'camera_specs' => 'Portrait 50-85mm lens, f/2-2.8',
                'default_lens' => '75mm',
                'default_aperture' => 'f/2',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['dialogue', 'connection', 'perspective', 'confrontation']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'documentary']),
                'prompt_template' => 'Over-the-shoulder shot with {subject}, dialogue framing, shallow focus on speaker',
                'motion_description' => 'Slight lateral drift maintaining conversation perspective',
                'compatible_transitions' => json_encode(['reverse-ots', 'close-up', 'medium', 'reaction']),
                'sort_order' => 26,
            ],
            [
                'slug' => 'pov',
                'name' => 'Point of View (POV)',
                'category' => 'angle',
                'description' => 'From character\'s eyes. Maximum immersion and subjectivity.',
                'camera_specs' => 'Normal lens 35-50mm, often handheld for realism',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['immersion', 'subjective', 'tension', 'discovery', 'fear']),
                'best_for_genres' => json_encode(['horror', 'thriller', 'action', 'vr']),
                'prompt_template' => 'POV shot from {subject}\'s perspective, first-person view, subjective camera',
                'motion_description' => 'Handheld subtle movement from character perspective',
                'compatible_transitions' => json_encode(['reaction', 'close-up', 'medium']),
                'sort_order' => 27,
            ],

            // ===== MOVEMENT SHOTS =====
            [
                'slug' => 'static',
                'name' => 'Static Shot',
                'category' => 'movement',
                'description' => 'Camera remains completely fixed. Emphasizes action within frame.',
                'camera_specs' => 'Any lens, locked-off tripod',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 10,
                'emotional_beats' => json_encode(['stability', 'observation', 'dialogue', 'tension-build']),
                'best_for_genres' => json_encode(['drama', 'documentary', 'comedy']),
                'prompt_template' => 'Static shot of {subject}, locked-off camera, action within frame',
                'motion_description' => 'Completely static, no camera movement',
                'compatible_transitions' => json_encode(['all']),
                'sort_order' => 30,
            ],
            [
                'slug' => 'pan',
                'name' => 'Pan',
                'category' => 'movement',
                'description' => 'Horizontal rotation on fixed axis. Reveals space or follows action.',
                'camera_specs' => 'Any lens, fluid head tripod',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['reveal', 'follow', 'scan', 'connection']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Pan shot following {subject}, horizontal camera rotation, {environment}',
                'motion_description' => 'Smooth horizontal pan following or revealing',
                'compatible_transitions' => json_encode(['static', 'tilt', 'wide']),
                'sort_order' => 31,
            ],
            [
                'slug' => 'tilt',
                'name' => 'Tilt',
                'category' => 'movement',
                'description' => 'Vertical rotation on fixed axis. Reveals height or scans vertically.',
                'camera_specs' => 'Any lens, fluid head tripod',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['reveal', 'scale', 'power', 'discovery']),
                'best_for_genres' => json_encode(['epic', 'documentary', 'thriller']),
                'prompt_template' => 'Tilt shot revealing {subject}, vertical camera rotation, scale emphasis',
                'motion_description' => 'Smooth vertical tilt up or down',
                'compatible_transitions' => json_encode(['static', 'pan', 'wide']),
                'sort_order' => 32,
            ],
            [
                'slug' => 'dolly',
                'name' => 'Dolly Shot',
                'category' => 'movement',
                'description' => 'Camera moves toward or away from subject. Creates intimacy or distance.',
                'camera_specs' => 'Any lens on dolly track, typically 35-85mm',
                'default_lens' => '50mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'emotional_beats' => json_encode(['intimacy', 'reveal', 'emphasis', 'tension', 'resolution']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'romance']),
                'prompt_template' => 'Dolly shot moving toward {subject}, smooth approach, {camera_movement}',
                'motion_description' => 'Smooth forward or backward dolly movement',
                'compatible_transitions' => json_encode(['static', 'close-up', 'medium']),
                'sort_order' => 33,
            ],
            [
                'slug' => 'tracking',
                'name' => 'Tracking Shot',
                'category' => 'movement',
                'description' => 'Camera follows alongside subject. Creates energy and journey.',
                'camera_specs' => 'Wide to normal lens, dolly or Steadicam, 24-50mm',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'emotional_beats' => json_encode(['journey', 'conversation', 'energy', 'pursuit']),
                'best_for_genres' => json_encode(['action', 'drama', 'documentary']),
                'prompt_template' => 'Tracking shot following {subject}, camera moving alongside, dynamic energy',
                'motion_description' => 'Smooth lateral tracking maintaining subject position',
                'compatible_transitions' => json_encode(['static', 'wide', 'medium']),
                'sort_order' => 34,
            ],
            [
                'slug' => 'crane',
                'name' => 'Crane Shot',
                'category' => 'movement',
                'description' => 'Vertical and horizontal movement. Epic, revealing, transitional.',
                'camera_specs' => 'Wide lens preferred, crane or jib arm, 24-35mm',
                'default_lens' => '24mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'emotional_beats' => json_encode(['epic', 'reveal', 'transition', 'triumph', 'conclusion']),
                'best_for_genres' => json_encode(['epic', 'drama', 'musical']),
                'prompt_template' => 'Crane shot rising above {subject}, sweeping vertical movement, epic scale',
                'motion_description' => 'Sweeping crane movement up, down, or combined',
                'compatible_transitions' => json_encode(['wide', 'establishing', 'aerial']),
                'sort_order' => 35,
            ],
            [
                'slug' => 'steadicam',
                'name' => 'Steadicam',
                'category' => 'movement',
                'description' => 'Smooth handheld following. Immersive, flowing, energetic.',
                'camera_specs' => 'Normal lens, Steadicam rig, 35-50mm',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 5,
                'typical_duration_max' => 60,
                'emotional_beats' => json_encode(['immersion', 'flow', 'energy', 'journey', 'tension']),
                'best_for_genres' => json_encode(['horror', 'thriller', 'action', 'drama']),
                'prompt_template' => 'Steadicam shot following {subject}, smooth floating movement, immersive flow',
                'motion_description' => 'Smooth floating movement following subject through space',
                'compatible_transitions' => json_encode(['static', 'wide', 'pov']),
                'sort_order' => 36,
            ],
            [
                'slug' => 'handheld',
                'name' => 'Handheld',
                'category' => 'movement',
                'description' => 'Intentional camera shake. Documentary realism, urgency, chaos.',
                'camera_specs' => 'Normal lens, shoulder or handheld, 35-50mm',
                'default_lens' => '35mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 10,
                'emotional_beats' => json_encode(['urgency', 'documentary', 'chaos', 'realism', 'tension']),
                'best_for_genres' => json_encode(['documentary', 'horror', 'action', 'war']),
                'prompt_template' => 'Handheld shot of {subject}, organic camera movement, documentary feel',
                'motion_description' => 'Organic handheld movement with natural shake',
                'compatible_transitions' => json_encode(['static', 'close-up', 'wide']),
                'sort_order' => 37,
            ],
            [
                'slug' => 'zoom',
                'name' => 'Zoom',
                'category' => 'movement',
                'description' => 'Lens focal length change. Emphasis, surprise, retro feel.',
                'camera_specs' => 'Zoom lens, 24-70mm or 70-200mm',
                'default_lens' => '24-70mm zoom',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['emphasis', 'surprise', 'reveal', 'retro']),
                'best_for_genres' => json_encode(['documentary', 'thriller', '70s-style']),
                'prompt_template' => 'Zoom shot on {subject}, focal length change, emphasis zoom',
                'motion_description' => 'Smooth or snap zoom in or out',
                'compatible_transitions' => json_encode(['static', 'close-up', 'wide']),
                'sort_order' => 38,
            ],
            [
                'slug' => 'dolly-zoom',
                'name' => 'Dolly Zoom (Vertigo)',
                'category' => 'movement',
                'description' => 'Dolly + opposite zoom. Disorienting, realization, famous Vertigo effect.',
                'camera_specs' => 'Zoom lens on dolly, 24-70mm',
                'default_lens' => '24-70mm zoom',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['disorientation', 'realization', 'horror', 'revelation']),
                'best_for_genres' => json_encode(['horror', 'thriller', 'psychological']),
                'prompt_template' => 'Dolly zoom on {subject}, Vertigo effect, disorienting perspective shift',
                'motion_description' => 'Simultaneous dolly and counter-zoom creating vertigo effect',
                'compatible_transitions' => json_encode(['close-up', 'reaction', 'wide']),
                'sort_order' => 39,
            ],
            [
                'slug' => 'whip-pan',
                'name' => 'Whip Pan',
                'category' => 'movement',
                'description' => 'Fast horizontal blur between subjects. Energy, transition, surprise.',
                'camera_specs' => 'Any lens, fast horizontal movement',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 1,
                'typical_duration_max' => 2,
                'emotional_beats' => json_encode(['transition', 'energy', 'surprise', 'time-passage']),
                'best_for_genres' => json_encode(['comedy', 'action', 'music-video']),
                'prompt_template' => 'Whip pan transition from {subject}, fast motion blur, energetic cut',
                'motion_description' => 'Rapid horizontal pan creating motion blur',
                'compatible_transitions' => json_encode(['static', 'medium', 'wide']),
                'sort_order' => 40,
            ],
            [
                'slug' => 'arc',
                'name' => 'Arc Shot',
                'category' => 'movement',
                'description' => 'Camera moves in circle around subject. Drama, revelation, 360 view.',
                'camera_specs' => 'Any lens on circular track or Steadicam, 35-50mm',
                'default_lens' => '40mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 5,
                'typical_duration_max' => 15,
                'emotional_beats' => json_encode(['drama', 'revelation', '360-view', 'tension', 'climax']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'action']),
                'prompt_template' => 'Arc shot circling {subject}, camera orbiting, dramatic reveal',
                'motion_description' => 'Camera arcing around subject in partial or full circle',
                'compatible_transitions' => json_encode(['static', 'close-up', 'medium']),
                'sort_order' => 41,
            ],

            // ===== FOCUS SHOTS =====
            [
                'slug' => 'rack-focus',
                'name' => 'Rack Focus',
                'category' => 'focus',
                'description' => 'Shift focus between subjects. Connection, reveal, transition.',
                'camera_specs' => 'Fast lens at wide aperture, f/1.4-2',
                'default_lens' => '85mm',
                'default_aperture' => 'f/1.4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 5,
                'emotional_beats' => json_encode(['connection', 'reveal', 'transition', 'discovery']),
                'best_for_genres' => json_encode(['drama', 'thriller', 'romance']),
                'prompt_template' => 'Rack focus between {subject}, shifting focus planes, connection reveal',
                'motion_description' => 'Focus pull between foreground and background subjects',
                'compatible_transitions' => json_encode(['static', 'close-up', 'medium']),
                'sort_order' => 50,
            ],
            [
                'slug' => 'deep-focus',
                'name' => 'Deep Focus',
                'category' => 'focus',
                'description' => 'Everything sharp front to back. Environment emphasis, staging.',
                'camera_specs' => 'Wide lens at narrow aperture, 24mm at f/8-11',
                'default_lens' => '24mm',
                'default_aperture' => 'f/8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 10,
                'emotional_beats' => json_encode(['environment', 'context', 'staging', 'complexity']),
                'best_for_genres' => json_encode(['drama', 'documentary', 'epic']),
                'prompt_template' => 'Deep focus shot of {subject}, everything sharp, environmental staging',
                'motion_description' => 'All planes in sharp focus, environmental awareness',
                'compatible_transitions' => json_encode(['shallow-focus', 'rack-focus', 'wide']),
                'sort_order' => 51,
            ],
            [
                'slug' => 'shallow-focus',
                'name' => 'Shallow Focus',
                'category' => 'focus',
                'description' => 'Subject sharp, background blurred. Isolation, intimacy, emphasis.',
                'camera_specs' => 'Fast lens wide open, 85mm at f/1.4',
                'default_lens' => '85mm',
                'default_aperture' => 'f/1.4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['isolation', 'intimacy', 'emphasis', 'beauty']),
                'best_for_genres' => json_encode(['drama', 'romance', 'portrait']),
                'prompt_template' => 'Shallow focus on {subject}, beautiful bokeh background, {lens_spec}',
                'motion_description' => 'Subject isolated with creamy out-of-focus background',
                'compatible_transitions' => json_encode(['deep-focus', 'rack-focus', 'close-up']),
                'sort_order' => 52,
            ],
            [
                'slug' => 'split-diopter',
                'name' => 'Split Diopter',
                'category' => 'focus',
                'description' => 'Two planes in focus simultaneously. Tension, dual focus, connection.',
                'camera_specs' => 'Split diopter filter, any lens',
                'default_lens' => '50mm + split diopter',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['dual-focus', 'tension', 'connection', 'contrast']),
                'best_for_genres' => json_encode(['thriller', 'horror', 'drama']),
                'prompt_template' => 'Split diopter shot of {subject}, dual focus planes, De Palma style',
                'motion_description' => 'Two distinct depth planes both in sharp focus',
                'compatible_transitions' => json_encode(['rack-focus', 'close-up', 'medium']),
                'sort_order' => 53,
            ],

            // ===== SPECIAL SHOTS =====
            [
                'slug' => 'two-shot',
                'name' => 'Two Shot',
                'category' => 'special',
                'description' => 'Two subjects in frame. Relationship, dialogue, comparison.',
                'camera_specs' => 'Normal lens, 35-50mm, f/2.8',
                'default_lens' => '40mm',
                'default_aperture' => 'f/2.8',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['relationship', 'dialogue', 'comparison', 'connection']),
                'best_for_genres' => json_encode(['drama', 'comedy', 'romance']),
                'prompt_template' => 'Two shot of {subject}, both subjects in frame, relationship framing',
                'motion_description' => 'Balanced framing of two subjects in conversation or interaction',
                'compatible_transitions' => json_encode(['over-shoulder', 'close-up', 'medium']),
                'sort_order' => 60,
            ],
            [
                'slug' => 'three-shot',
                'name' => 'Three Shot',
                'category' => 'special',
                'description' => 'Three subjects in frame. Group dynamics, hierarchy, triangle.',
                'camera_specs' => 'Wide to normal lens, 35mm, f/4',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['group-dynamics', 'triangle', 'hierarchy', 'conflict']),
                'best_for_genres' => json_encode(['drama', 'comedy', 'thriller']),
                'prompt_template' => 'Three shot of {subject}, all three subjects visible, group dynamics',
                'motion_description' => 'Balanced framing of three subjects showing relationships',
                'compatible_transitions' => json_encode(['two-shot', 'medium', 'wide']),
                'sort_order' => 61,
            ],
            [
                'slug' => 'master',
                'name' => 'Master Shot',
                'category' => 'special',
                'description' => 'Wide coverage of entire scene. Reference, geography, editing safety.',
                'camera_specs' => 'Wide lens, 24-35mm, f/4-5.6',
                'default_lens' => '28mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 5,
                'typical_duration_max' => 60,
                'emotional_beats' => json_encode(['establishing', 'geography', 'reference', 'context']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Master shot of {subject}, wide scene coverage, full geography visible',
                'motion_description' => 'Complete scene coverage for reference and editing',
                'compatible_transitions' => json_encode(['medium', 'close-up', 'two-shot']),
                'sort_order' => 62,
            ],
            [
                'slug' => 'reaction',
                'name' => 'Reaction Shot',
                'category' => 'special',
                'description' => 'Subject responding to off-screen event. Emotion, impact, comedy.',
                'camera_specs' => 'Portrait lens, 50-85mm, f/2',
                'default_lens' => '75mm',
                'default_aperture' => 'f/2',
                'typical_duration_min' => 1,
                'typical_duration_max' => 4,
                'emotional_beats' => json_encode(['emotion', 'impact', 'comedy', 'surprise', 'realization']),
                'best_for_genres' => json_encode(['comedy', 'drama', 'horror']),
                'prompt_template' => 'Reaction shot of {subject}, emotional response, expressive framing',
                'motion_description' => 'Quick responsive framing capturing emotional reaction',
                'compatible_transitions' => json_encode(['reverse', 'close-up', 'medium']),
                'sort_order' => 63,
            ],
            [
                'slug' => 'establishing',
                'name' => 'Establishing Shot',
                'category' => 'special',
                'description' => 'Sets location and context. Opening shot, scene transitions.',
                'camera_specs' => 'Wide lens, 16-24mm, f/5.6-8',
                'default_lens' => '21mm',
                'default_aperture' => 'f/5.6',
                'typical_duration_min' => 3,
                'typical_duration_max' => 8,
                'emotional_beats' => json_encode(['opening', 'transition', 'geography', 'context', 'mood']),
                'best_for_genres' => json_encode(['all']),
                'prompt_template' => 'Establishing shot of {environment}, location context, {camera_movement}',
                'motion_description' => 'Slow reveal of location and atmosphere',
                'compatible_transitions' => json_encode(['wide', 'medium', 'tracking']),
                'sort_order' => 64,
            ],
            [
                'slug' => 'weather',
                'name' => 'Weather Shot',
                'category' => 'special',
                'description' => 'Atmospheric/environmental shot. Mood, transition, time passage.',
                'camera_specs' => 'Any lens, often wide for environment',
                'default_lens' => '35mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 2,
                'typical_duration_max' => 6,
                'emotional_beats' => json_encode(['mood', 'transition', 'time-passage', 'atmosphere']),
                'best_for_genres' => json_encode(['drama', 'horror', 'documentary']),
                'prompt_template' => 'Weather shot of {environment}, atmospheric conditions, mood setting',
                'motion_description' => 'Atmospheric environmental capture',
                'compatible_transitions' => json_encode(['establishing', 'wide', 'cutaway']),
                'sort_order' => 65,
            ],
            [
                'slug' => 'aerial',
                'name' => 'Aerial Shot',
                'category' => 'special',
                'description' => 'Filmed from above (drone/helicopter). Scale, journey, epic.',
                'camera_specs' => 'Wide lens on drone/helicopter, 24mm',
                'default_lens' => '24mm',
                'default_aperture' => 'f/4',
                'typical_duration_min' => 4,
                'typical_duration_max' => 15,
                'emotional_beats' => json_encode(['scale', 'journey', 'epic', 'freedom', 'overview']),
                'best_for_genres' => json_encode(['epic', 'documentary', 'action', 'travel']),
                'prompt_template' => 'Aerial shot of {subject}, drone perspective, {environment} from above',
                'motion_description' => 'Sweeping aerial movement revealing landscape',
                'compatible_transitions' => json_encode(['establishing', 'wide', 'crane']),
                'sort_order' => 66,
            ],
        ];

        foreach ($shotTypes as $shotType) {
            VwShotType::updateOrCreate(
                ['slug' => $shotType['slug']],
                array_merge($shotType, ['is_active' => true])
            );
        }
    }
}
